import { createContext, useContext, useState } from 'react'

const strings = {
  en: {
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    profile: 'Profile',
    enterCode: 'Enter Code',
    start: 'Start',
    back: 'Back',
    xp: 'XP',
    badges: 'Badges',
    name: 'Your Name',
    avatar: 'Pick Avatar',
    waiting: 'Waiting for players...',
    noGames: 'No games available',
    pickGame: 'Pick a Game',
    players: 'Players',
    rules: 'Rules',
    guess: 'Your Guess',
    submit: 'Submit Guess',
    reveal: 'Reveal Answer',
    winner: 'Winner!',
    score: 'Score',
    play: 'Play',
    comingSoon: 'Coming Soon',
    roomNotFound: 'Room not found. Check the code and try again.',
    pause: 'Pause',
    returnHome: 'Return Home',
    resume: 'Resume',
    newGame: 'New Game',
    resumeGame: 'Resume Game',
    gamesInProgress: 'Continue playing',
    save: 'Save',
    savedSuccess: 'Saved!',
    noBadgesYet: 'Play games to earn badges!',
    onlineGames: 'Online Games',
    needsInternet: 'Needs internet',
    createRoomFailed: 'Failed to create room. Check your connection.',
    connectionLost: 'Connection lost — Reconnecting...',
    luckyGuesser: '🔢 Lucky Guesser',
    endGame: 'End Game',
    removePlayer: 'Remove',
    roomExpired: 'Room has expired. Please create a new room.',
    kickedFromRoom: 'You were removed from the room.',
    pickStartNumber: 'Pick a starting number (1–999)',
    startChain: 'Start Chain',
    waitingForStart: 'Waiting for host to pick a starting number…',
    changeLog: 'Change Log',
    applyChange: 'Apply',
    noChangesYet: 'No changes yet.',
    casualRoom: 'Casual',
    rankedRoom: 'Ranked',
    casualDesc: 'Just for fun — standard XP',
    rankedDesc: 'XP ×1.2 + win tracked',
    roomClosesIn: 'Room closes in',
    rapidFireBattle: 'FirstBell',
    pickCategory: 'Pick a Category',
    timeLeft: 'Time left',
    correctAnswer: 'Correct Answer',
    yourScore: 'Your Score',
    rankedBonus: 'Ranked Bonus!',
    level: 'Level',
    wins: 'Wins',
    gamesPlayed: 'Played',
    round: 'Round',
    of: 'of',
    rajaMantriTitle: 'Raja Mantri Chor Sipahi',
    roleRaja: 'Raja',
    roleMantri: 'Mantri',
    roleChor: 'Chor',
    roleSipahi: 'Sipahi',
    roleDescRaja: 'You score 1000 points, no matter what.',
    roleDescMantri: 'Guess who the Chor is. Get it right and you keep your points.',
    roleDescChor: 'Stay hidden. If the Mantri guesses wrong, you steal their points.',
    roleDescSipahi: 'You score 500 points, no matter what.',
    youAreThe: 'You are the',
    gotIt: 'Got it',
    waitingWithCount: 'Waiting…',
    whoIsTheChor: 'Who is the Chor?',
    mantriIsChoosing: 'The Mantri is deciding who the Chor is…',
    lockedInWaiting: 'Locked in — waiting for the reveal…',
    mantriCaughtChor: 'The Mantri caught the Chor!',
    chorGotAway: 'The Chor got away!',
    scoreboard: 'Scoreboard',
    nextRound: 'Next Round',
    seeFinalResults: 'See Final Results',
    waitingForHostContinue: 'Waiting for the host to continue…',
    waitingForHostStart: 'Waiting for the host to start the game…',
    rounds: 'Rounds',
    startGame: 'Start Game',
    starting: 'Starting…',
    winner: 'Winner',
    rematch: 'Rematch',
    voteRematch: 'Vote Rematch',
    home: 'Home',
  },
  hi: {
    createRoom: 'कमरा बनाएं',
    joinRoom: 'कमरे में जाएं',
    profile: 'प्रोफाइल',
    enterCode: 'कोड डालें',
    start: 'शुरू करें',
    back: 'वापस',
    xp: 'XP',
    badges: 'बैज',
    name: 'आपका नाम',
    avatar: 'अवतार चुनें',
    waiting: 'खिलाड़ियों का इंतज़ार...',
    noGames: 'कोई खेल नहीं',
    pickGame: 'खेल चुनें',
    players: 'खिलाड़ी',
    rules: 'नियम',
    guess: 'आपका अनुमान',
    submit: 'अनुमान भेजें',
    reveal: 'जवाब देखें',
    winner: 'विजेता!',
    score: 'अंक',
    play: 'खेलें',
    comingSoon: 'जल्द आ रहा है',
    roomNotFound: 'कमरा नहीं मिला। कोड जाँचें और दोबारा कोशिश करें।',
    pause: 'रोकें',
    returnHome: 'घर वापस',
    resume: 'जारी रखें',
    newGame: 'नया खेल',
    resumeGame: 'खेल जारी रखें',
    gamesInProgress: 'खेल जारी रखें',
    save: 'सेव करें',
    savedSuccess: 'सेव हो गया!',
    noBadgesYet: 'बैज कमाने के लिए खेलें!',
    onlineGames: 'ऑनलाइन गेम',
    needsInternet: 'इंटरनेट चाहिए',
    createRoomFailed: 'कमरा नहीं बना। कनेक्शन जाँचें।',
    connectionLost: 'कनेक्शन टूट गया — फिर से जोड़ रहे हैं...',
    luckyGuesser: '🔢 भाग्यशाली अनुमानकर्ता',
    endGame: 'खेल खत्म करें',
    removePlayer: 'हटाएं',
    roomExpired: 'कमरा समाप्त हो गया। नया कमरा बनाएं।',
    kickedFromRoom: 'आपको कमरे से हटा दिया गया।',
    pickStartNumber: 'शुरुआती नंबर चुनें (1–999)',
    startChain: 'चेन शुरू करें',
    waitingForStart: 'होस्ट के नंबर चुनने का इंतज़ार…',
    changeLog: 'बदलाव लॉग',
    applyChange: 'लागू करें',
    noChangesYet: 'अभी कोई बदलाव नहीं।',
    casualRoom: 'कैज़ुअल',
    rankedRoom: 'रैंक्ड',
    casualDesc: 'मज़े के लिए — सामान्य XP',
    rankedDesc: 'XP ×1.2 + जीत रिकॉर्ड',
    roomClosesIn: 'कमरा बंद होगा',
    rapidFireBattle: 'फर्स्टबेल',
    pickCategory: 'श्रेणी चुनें',
    timeLeft: 'समय बाकी',
    correctAnswer: 'सही जवाब',
    yourScore: 'आपका स्कोर',
    rankedBonus: 'रैंक्ड बोनस!',
    level: 'स्तर',
    wins: 'जीत',
    gamesPlayed: 'खेले',
    round: 'राउंड',
    of: 'में से',
    rajaMantriTitle: 'राजा मंत्री चोर सिपाही',
    roleRaja: 'राजा',
    roleMantri: 'मंत्री',
    roleChor: 'चोर',
    roleSipahi: 'सिपाही',
    roleDescRaja: 'आपको 1000 अंक मिलेंगे, चाहे कुछ भी हो।',
    roleDescMantri: 'अंदाज़ा लगाएं कि चोर कौन है। सही अंदाज़ा लगाने पर आपके अंक बरकरार रहेंगे।',
    roleDescChor: 'छुपे रहें। अगर मंत्री गलत अंदाज़ा लगाता है, तो आप उसके अंक ले लेंगे।',
    roleDescSipahi: 'आपको 500 अंक मिलेंगे, चाहे कुछ भी हो।',
    youAreThe: 'आप हैं',
    gotIt: 'समझ गया',
    waitingWithCount: 'इंतज़ार…',
    whoIsTheChor: 'चोर कौन है?',
    mantriIsChoosing: 'मंत्री तय कर रहे हैं कि चोर कौन है…',
    lockedInWaiting: 'लॉक हो गया — खुलासे का इंतज़ार…',
    mantriCaughtChor: 'मंत्री ने चोर को पकड़ लिया!',
    chorGotAway: 'चोर भाग निकला!',
    scoreboard: 'स्कोरबोर्ड',
    nextRound: 'अगला राउंड',
    seeFinalResults: 'अंतिम परिणाम देखें',
    waitingForHostContinue: 'होस्ट के जारी रखने का इंतज़ार…',
    waitingForHostStart: 'होस्ट के खेल शुरू करने का इंतज़ार…',
    rounds: 'राउंड',
    startGame: 'खेल शुरू करें',
    starting: 'शुरू हो रहा है…',
    winner: 'विजेता',
    rematch: 'फिर से खेलें',
    voteRematch: 'फिर से खेलने हेतु वोट करें',
    home: 'होम',
  }
}

const LangContext = createContext()

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = (key) => strings[lang][key] ?? key
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
