import { createContext, useContext, useState } from 'react'

const strings = {
  en: {
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    profile: 'Profile',
    enterCode: 'Enter Code',
    start: 'Start',
    back: 'Back',
    xp: 'XP',
    badges: 'Badges',
    name: 'Your Name',
    avatar: 'Pick Avatar',
    waiting: 'Waiting for players...',
    noGames: 'No games available',
    pickGame: 'Pick a Game',
    players: 'Players',
    rules: 'Rules',
    guess: 'Your Guess',
    submit: 'Submit Guess',
    reveal: 'Reveal Answer',
    winner: 'Winner!',
    score: 'Score',
    play: 'Play',
    comingSoon: 'Coming Soon',
    roomNotFound: 'Room not found. Check the code and try again.',
    pause: 'Pause',
    returnHome: 'Return Home',
    resume: 'Resume',
    newGame: 'New Game',
    resumeGame: 'Resume Game',
    gamesInProgress: 'Continue playing',
    save: 'Save',
    savedSuccess: 'Saved!',
    noBadgesYet: 'Play games to earn badges!',
    onlineGames: 'Online Games',
    needsInternet: 'Needs internet',
    createRoomFailed: 'Failed to create room. Check your connection.',
    connectionLost: 'Connection lost — Reconnecting...',
    luckyGuesser: '🔢 Lucky Guesser',
    endGame: 'End Game',
    removePlayer: 'Remove',
    roomExpired: 'Room has expired. Please create a new room.',
    kickedFromRoom: 'You were removed from the room.',
    pickStartNumber: 'Pick a starting number (1–999)',
    startChain: 'Start Chain',
    waitingForStart: 'Waiting for host to pick a starting number…',
    changeLog: 'Change Log',
    applyChange: 'Apply',
    noChangesYet: 'No changes yet.',
    casualRoom: 'Casual',
    rankedRoom: 'Ranked',
    casualDesc: 'Just for fun — standard XP',
    rankedDesc: 'XP ×1.2 + win tracked',
    roomClosesIn: 'Room closes in',
    rapidFireBattle: 'FirstBell',
    pickCategory: 'Pick a Category',
    timeLeft: 'Time left',
    correctAnswer: 'Correct Answer',
    yourScore: 'Your Score',
    rankedBonus: 'Ranked Bonus!',
    level: 'Level',
    wins: 'Wins',
    gamesPlayed: 'Played',
  },
  hi: {
    createRoom: 'कमरा बनाएं',
    joinRoom: 'कमरे में जाएं',
    profile: 'प्रोफाइल',
    enterCode: 'कोड डालें',
    start: 'शुरू करें',
    back: 'वापस',
    xp: 'XP',
    badges: 'बैज',
    name: 'आपका नाम',
    avatar: 'अवतार चुनें',
    waiting: 'खिलाड़ियों का इंतज़ार...',
    noGames: 'कोई खेल नहीं',
    pickGame: 'खेल चुनें',
    players: 'खिलाड़ी',
    rules: 'नियम',
    guess: 'आपका अनुमान',
    submit: 'अनुमान भेजें',
    reveal: 'जवाब देखें',
    winner: 'विजेता!',
    score: 'अंक',
    play: 'खेलें',
    comingSoon: 'जल्द आ रहा है',
    roomNotFound: 'कमरा नहीं मिला। कोड जाँचें और दोबारा कोशिश करें।',
    pause: 'रोकें',
    returnHome: 'घर वापस',
    resume: 'जारी रखें',
    newGame: 'नया खेल',
    resumeGame: 'खेल जारी रखें',
    gamesInProgress: 'खेल जारी रखें',
    save: 'सेव करें',
    savedSuccess: 'सेव हो गया!',
    noBadgesYet: 'बैज कमाने के लिए खेलें!',
    onlineGames: 'ऑनलाइन गेम',
    needsInternet: 'इंटरनेट चाहिए',
    createRoomFailed: 'कमरा नहीं बना। कनेक्शन जाँचें।',
    connectionLost: 'कनेक्शन टूट गया — फिर से जोड़ रहे हैं...',
    luckyGuesser: '🔢 भाग्यशाली अनुमानकर्ता',
    endGame: 'खेल खत्म करें',
    removePlayer: 'हटाएं',
    roomExpired: 'कमरा समाप्त हो गया। नया कमरा बनाएं।',
    kickedFromRoom: 'आपको कमरे से हटा दिया गया।',
    pickStartNumber: 'शुरुआती नंबर चुनें (1–999)',
    startChain: 'चेन शुरू करें',
    waitingForStart: 'होस्ट के नंबर चुनने का इंतज़ार…',
    changeLog: 'बदलाव लॉग',
    applyChange: 'लागू करें',
    noChangesYet: 'अभी कोई बदलाव नहीं।',
    casualRoom: 'कैज़ुअल',
    rankedRoom: 'रैंक्ड',
    casualDesc: 'मज़े के लिए — सामान्य XP',
    rankedDesc: 'XP ×1.2 + जीत रिकॉर्ड',
    roomClosesIn: 'कमरा बंद होगा',
    rapidFireBattle: 'फर्स्टबेल',
    pickCategory: 'श्रेणी चुनें',
    timeLeft: 'समय बाकी',
    correctAnswer: 'सही जवाब',
    yourScore: 'आपका स्कोर',
    rankedBonus: 'रैंक्ड बोनस!',
    level: 'स्तर',
    wins: 'जीत',
    gamesPlayed: 'खेले',
  }
}

const LangContext = createContext()

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = (key) => strings[lang][key] ?? key
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
