/**
 * Unified question bank — shared by FirstBell and Tez Dimaag Challenge.
 *
 * Canonical schema: { category, difficulty, question, options: [string×4], correctIdx: 0|1|2|3 }
 *
 * Category keys: 'gk' | 'bollywood' | 'cricket' | 'science' | 'food' | 'modern' | 'brain'
 * Difficulty:    'easy' | 'medium' | 'hard'
 */

function shuffle(arr) {
  const out = [...arr]
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

export const ALL_QUESTIONS = [
  // ─── GK ───────────────────────────────────────────────────────────────────
  { category: 'gk', difficulty: 'easy',   question: 'What is the capital of India?', options: ['New Delhi', 'Mumbai', 'Kolkata', 'Chennai'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'How many states does India have?', options: ['28', '29', '27', '30'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Who was the first Prime Minister of India?', options: ['Jawaharlal Nehru', 'Sardar Patel', 'Rajendra Prasad', 'Subhas Bose'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which is the national bird of India?', options: ['Peacock', 'Parrot', 'Sparrow', 'Eagle'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which festival is known as the festival of lights?', options: ['Diwali', 'Holi', 'Eid', 'Christmas'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'What is the national animal of India?', options: ['Tiger', 'Lion', 'Elephant', 'Peacock'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Which state has the longest coastline?', options: ['Gujarat', 'Andhra Pradesh', 'Tamil Nadu', 'Maharashtra'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'In which year did India become a republic?', options: ['1950', '1947', '1952', '1948'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which city is known as the Pink City?', options: ['Jaipur', 'Jodhpur', 'Udaipur', 'Jaisalmer'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Who wrote the national anthem of India?', options: ['Rabindranath Tagore', 'Bankim Chandra', 'Sarojini Naidu', 'Subhas Bose'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which is the largest state by area in India?', options: ['Rajasthan', 'Madhya Pradesh', 'Maharashtra', 'Uttar Pradesh'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which river is considered the holiest in India?', options: ['Ganga', 'Yamuna', 'Brahmaputra', 'Godavari'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'What is the currency of India?', options: ['Rupee', 'Taka', 'Rupiah', 'Peso'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which monument is located in Agra?', options: ['Taj Mahal', 'Red Fort', 'Qutub Minar', 'India Gate'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which city is known as the financial capital of India?', options: ['Mumbai', 'Delhi', 'Bangalore', 'Chennai'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Which state produces the most tea in India?', options: ['Assam', 'West Bengal', 'Kerala', 'Tamil Nadu'], correctIdx: 0 },
  { category: 'gk', difficulty: 'hard',   question: 'Which article of the Indian constitution abolished untouchability?', options: ['Article 17', 'Article 15', 'Article 14', 'Article 16'], correctIdx: 0 },
  { category: 'gk', difficulty: 'hard',   question: 'Who designed the Indian national flag?', options: ['Pingali Venkayya', 'Mahatma Gandhi', 'Nehru', 'Sardar Patel'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'How many union territories does India have?', options: ['8', '7', '9', '6'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which state has the highest population in India?', options: ['Uttar Pradesh', 'Maharashtra', 'Bihar', 'West Bengal'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Who was the first President of India?', options: ['Rajendra Prasad', 'Jawaharlal Nehru', 'Radhakrishnan', 'Zakir Hussain'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Which mountain range separates India from Tibet?', options: ['Himalayas', 'Western Ghats', 'Vindhyas', 'Aravallis'], correctIdx: 0 },
  { category: 'gk', difficulty: 'hard',   question: 'In which year was the first Lok Sabha election held?', options: ['1952', '1950', '1947', '1951'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which river flows through the city of Delhi?', options: ['Yamuna', 'Ganga', 'Sutlej', 'Brahmaputra'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which festival is played with colors?', options: ['Holi', 'Diwali', 'Eid', 'Pongal'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: "What is the name of India's space agency?", options: ['ISRO', 'NASA', 'ESA', 'DRDO'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Which city hosted the 2010 Commonwealth Games?', options: ['Delhi', 'Mumbai', 'Bangalore', 'Chennai'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'The Sundarbans mangrove forest is shared between India and which country?', options: ['Bangladesh', 'Myanmar', 'Sri Lanka', 'Nepal'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Which state is known as the "Spice Garden of India"?', options: ['Kerala', 'Goa', 'Karnataka', 'Tamil Nadu'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which Indian city is known as the "City of Joy"?', options: ['Kolkata', 'Mumbai', 'Delhi', 'Chennai'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'What is the highest civilian award in India?', options: ['Bharat Ratna', 'Padma Vibhushan', 'Padma Bhushan', 'Padma Shri'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which ocean lies to the south of India?', options: ['Indian Ocean', 'Pacific Ocean', 'Atlantic Ocean', 'Arctic Ocean'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Which dam on the Bhakra River is the highest gravity dam in India?', options: ['Bhakra Dam', 'Hirakud Dam', 'Nagarjunasagar Dam', 'Tehri Dam'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Who gave the slogan "Jai Hind"?', options: ['Subhas Chandra Bose', 'Mahatma Gandhi', 'Nehru', 'Bhagat Singh'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which is the smallest state of India by area?', options: ['Goa', 'Sikkim', 'Tripura', 'Nagaland'], correctIdx: 0 },
  { category: 'gk', difficulty: 'medium', question: 'Which Indian ruler built the Red Fort in Delhi?', options: ['Shah Jahan', 'Aurangzeb', 'Akbar', 'Babur'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: "Which sport is India's national game?", options: ['Hockey', 'Cricket', 'Football', 'Kabaddi'], correctIdx: 0 },
  { category: 'gk', difficulty: 'easy',   question: 'Which Indian city is the Silicon Valley of India?', options: ['Bangalore', 'Hyderabad', 'Pune', 'Chennai'], correctIdx: 0 },

  // ─── BOLLYWOOD ────────────────────────────────────────────────────────────
  { category: 'bollywood', difficulty: 'easy',   question: 'Who directed the film "3 Idiots"?', options: ['Rajkumar Hirani', 'Karan Johar', 'Farhan Akhtar', 'Anurag Kashyap'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which actor played the lead role in "Dangal"?', options: ['Aamir Khan', 'Salman Khan', 'Akshay Kumar', 'Hrithik Roshan'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which OTT platform streams "Sacred Games"?', options: ['Netflix', 'Amazon Prime', 'Disney+ Hotstar', 'ZEE5'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Who directed "Bahubali"?', options: ['S.S. Rajamouli', 'Shankar', 'Trivikram', 'Koratala Siva'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Who composed the music for "Rockstar"?', options: ['A.R. Rahman', 'Pritam', 'Amit Trivedi', 'Vishal-Shekhar'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which web series features Pratik Gandhi as Harshad Mehta?', options: ['Scam 1992', 'The Family Man', 'Made in Heaven', 'Delhi Crime'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Who played the antagonist in "Jawan" (2023)?', options: ['Vijay Sethupathi', 'Nawazuddin Siddiqui', 'Kay Kay Menon', 'John Abraham'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Who directed "Taare Zameen Par"?', options: ['Aamir Khan', 'Ashutosh Gowariker', 'Rajkumar Hirani', 'Nitesh Tiwari'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which actress played Geet in "Jab We Met"?', options: ['Kareena Kapoor', 'Katrina Kaif', 'Deepika Padukone', 'Priyanka Chopra'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which film features the song "Gerua"?', options: ['Dilwale', 'Chennai Express', 'Jab Tak Hai Jaan', 'Raees'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Who directed "Gully Boy"?', options: ['Zoya Akhtar', 'Farhan Akhtar', 'Reema Kagti', 'Kabir Khan'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which film has the song "Badtameez Dil"?', options: ['Yeh Jawaani Hai Deewani', 'Rockstar', 'Barfi', 'Tamasha'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which actor played the role of PK in the 2014 film?', options: ['Aamir Khan', 'Shah Rukh Khan', 'Salman Khan', 'Ranbir Kapoor'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'In which film did Sushant Singh Rajput play the lead?', options: ['Chhichhore', 'Stree', 'Bard of Blood', 'Raazi'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Who won Best Actress National Award for "Queen"?', options: ['Kangana Ranaut', 'Deepika Padukone', 'Priyanka Chopra', 'Alia Bhatt'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which film is based on the 26/11 Mumbai attacks?', options: ['A Wednesday', 'Neerja', 'Hotel Mumbai', 'The Attacks of 26/11'], correctIdx: 3 },
  { category: 'bollywood', difficulty: 'medium', question: 'Who directed "Dil Dhadakne Do"?', options: ['Zoya Akhtar', 'Karan Johar', 'Farhan Akhtar', 'Imtiaz Ali'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: 'Which Bollywood film won the Oscar for Best Foreign Language Film?', options: ['None — no Indian film has won', 'Lagaan', 'Mother India', 'Salaam Bombay'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Who starred in both "Kabhi Khushi Kabhie Gham" and "Kal Ho Naa Ho"?', options: ['Shah Rukh Khan', 'Hrithik Roshan', 'Salman Khan', 'Aamir Khan'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which streaming show is set in the city of Mirzapur?', options: ['Mirzapur', 'Panchayat', 'TVF Pitchers', 'Kota Factory'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which film starred Alia Bhatt as an undercover agent?', options: ['Raazi', 'Udta Punjab', 'Highway', 'Kapoor & Sons'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Who played Alauddin Khilji in "Padmaavat"?', options: ['Ranveer Singh', 'Ranbir Kapoor', 'Shahid Kapoor', 'Arjun Kapoor'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which film had Vidya Balan playing a Bihari woman detective?', options: ['Kahaani', 'Dirty Picture', 'Tumhari Sulu', 'Shakuntala Devi'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'In "DDLJ", what does Raj give Simran at the end to let her board the train?', options: ['His hand (on the train)', 'A letter', 'A rose', 'A ring'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which Bollywood actor is also known as "Bhai" by fans?', options: ['Salman Khan', 'Aamir Khan', 'Shah Rukh Khan', 'Akshay Kumar'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which film stars Ayushmann Khurrana as a sperm donor?', options: ['Vicky Donor', 'Badhaai Ho', 'Article 15', 'Dream Girl'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: 'Which director made "Gangs of Wasseypur"?', options: ['Anurag Kashyap', 'Vishal Bhardwaj', 'Dibakar Banerjee', 'Tigmanshu Dhulia'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which 2022 RRR song won the Academy Award (Oscar)?', options: ['Naatu Naatu', 'Komuram Bheemudo', 'Janani', 'Dosti'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: 'Who played the role of Sardar Patel in the film "Sardar"?', options: ['Paresh Rawal', 'Manoj Bajpayee', 'Naseeruddin Shah', 'Om Puri'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which Bollywood movie is a remake of the Hollywood film "Hitch"?', options: ['Partner', 'Pyaar Ka Punchnama', 'Ek Main Aur Ekk Tu', 'Ishq Vishk'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: 'Who directed "The Lunchbox" (2013)?', options: ['Ritesh Batra', 'Anurag Basu', 'Vishal Bhardwaj', 'Dibakar Banerjee'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which actor made his debut in "Ishq Vishk" (2003)?', options: ['Shahid Kapoor', 'Ranbir Kapoor', 'Imran Khan', 'Sharman Joshi'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: "In \"Deewar\" (1975), what does Amitabh's character say about his mother?", options: ['Mere paas maa hai', 'Main aaj bhi feke hue paise…', 'Tumhara paap mujhe maloom hai', 'Saat saal baad dekha'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which music director composed the score for "Sholay"?', options: ['R.D. Burman', 'S.D. Burman', 'Naushad', 'Laxmikant-Pyarelal'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: 'Which film features the iconic "Ek Do Teen" song performed by Madhuri Dixit?', options: ['Tezaab', 'Ram Lakhan', 'Beta', 'Khalnayak'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: 'Who directed "Mughal-e-Azam" (1960)?', options: ['K. Asif', 'Mehboob Khan', 'Bimal Roy', 'Guru Dutt'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: "Deepika Padukone's debut Bollywood film was?", options: ['Om Shanti Om', 'Love Aaj Kal', 'Bachna Ae Haseeno', 'Cocktail'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which film stars Ranveer Singh as a Maratha warrior?', options: ['Bajirao Mastani', 'Ram-Leela', 'Padmaavat', 'Simmba'], correctIdx: 0 },
  // TDC-unique Bollywood
  { category: 'bollywood', difficulty: 'easy',   question: "What is the name of the tiger in \"Ek Tha Tiger\"?", options: ['Tiger', 'Sher', 'Baagh', 'No name given'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'easy',   question: "Which film has the song 'Tujh Mein Rab Dikhta Hai'?", options: ['Rab Ne Bana Di Jodi', 'Veer-Zaara', 'Mohabbatein', 'Kal Ho Naa Ho'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'medium', question: 'Which film won Best Film at the 2023 National Awards?', options: ['RRR', 'The Kashmir Files', 'Kantara', 'Gangubai Kathiawadi'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: "Who wrote the dialogues for 'Gangs of Wasseypur'?", options: ['Zeishan Quadri', 'Anurag Kashyap', 'Varun Grover', 'Akshat Verma'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: "Which 1995 film had the tagline 'A Love Legend'?", options: ['Dilwale Dulhania Le Jayenge', 'Hum Aapke Hain Koun', 'Raja Hindustani', 'Kuch Kuch Hota Hai'], correctIdx: 0 },
  { category: 'bollywood', difficulty: 'hard',   question: 'Which of these classic films did NOT feature Amitabh Bachchan?', options: ['Deewar', 'Sholay', 'Don', 'Mughal-e-Azam'], correctIdx: 3 },

  // ─── CRICKET ──────────────────────────────────────────────────────────────
  { category: 'cricket', difficulty: 'easy',   question: 'How many runs is a six worth?', options: ['6', '4', '2', '1'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'How many players are in a cricket team?', options: ['11', '10', '12', '9'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Who is known as "Captain Cool" in cricket?', options: ['MS Dhoni', 'Virat Kohli', 'Rohit Sharma', 'Rahul Dravid'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'In which year did India win the first ODI World Cup?', options: ['1983', '2011', '2007', '1996'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'Who took all 10 wickets in a Test innings for India?', options: ['Anil Kumble', 'Kapil Dev', 'Harbhajan Singh', 'Ashwin'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Which country has won the most ODI World Cups?', options: ['Australia', 'India', 'West Indies', 'England'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'Who scored 400 not out in a Test match?', options: ['Brian Lara', 'Matthew Hayden', 'Sehwag', 'Sachin'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: "Who was India's captain in the 1983 World Cup?", options: ['Kapil Dev', 'Sunil Gavaskar', 'Mohinder Amarnath', 'Kirti Azad'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: 'Which team has won the most IPL titles?', options: ['Mumbai Indians', 'Chennai Super Kings', 'Kolkata Knight Riders', 'Rajasthan Royals'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'How many balls are there in one over?', options: ['6', '4', '8', '5'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Who has the most runs in international cricket?', options: ['Sachin Tendulkar', 'Ricky Ponting', 'Jacques Kallis', 'Virat Kohli'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'Who hit six sixes in one over in T20 World Cup?', options: ['Yuvraj Singh', 'Herschelle Gibbs', 'Kieron Pollard', 'Chris Gayle'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Which Indian city hosts the Royal Challengers IPL team?', options: ['Bangalore', 'Mumbai', 'Chennai', 'Kolkata'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'What does LBW stand for?', options: ['Leg Before Wicket', 'Long Ball Wide', 'Left Behind Wicket', 'Leg Bye Wicket'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: 'Who was the first Indian to score a triple century in Tests?', options: ['Virender Sehwag', 'Sachin Tendulkar', 'Rahul Dravid', 'Karun Nair'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Which format has 20 overs per side?', options: ['T20', 'ODI', 'Test', 'T10'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'Who won the 2023 Cricket World Cup?', options: ['Australia', 'India', 'England', 'New Zealand'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Which Indian batter has the most IPL runs?', options: ['Virat Kohli', 'Rohit Sharma', 'MS Dhoni', 'Suresh Raina'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'What is a "duck" in cricket?', options: ['Out for zero', 'A type of shot', 'A field position', 'No ball'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Who is known as "Hitman" in cricket?', options: ['Rohit Sharma', 'Virat Kohli', 'MS Dhoni', 'Hardik Pandya'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: 'Which country hosted the first T20 World Cup?', options: ['South Africa', 'England', 'India', 'West Indies'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: 'Who took a hat-trick in the 1987 World Cup for India?', options: ['Chetan Sharma', 'Kapil Dev', 'Maninder Singh', 'Ravi Shastri'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'What is the length of a cricket pitch in yards?', options: ['22', '20', '24', '18'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'Which Indian bowler has taken the most Test wickets?', options: ['Anil Kumble', 'Kapil Dev', 'Ravichandran Ashwin', 'Harbhajan Singh'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Who won the 2011 Cricket World Cup?', options: ['India', 'Sri Lanka', 'Pakistan', 'Australia'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'In which city is the Eden Gardens cricket stadium?', options: ['Kolkata', 'Mumbai', 'Delhi', 'Chennai'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: 'Who holds the record for highest individual Test score in cricket?', options: ['Brian Lara (400*)', 'Sachin Tendulkar (248*)', 'Matthew Hayden (380)', 'Wally Hammond (336*)'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'How many wickets are on a cricket pitch in total (both ends)?', options: ['6', '3', '9', '4'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Which country invented cricket?', options: ['England', 'Australia', 'India', 'West Indies'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Which Indian cricketer is called "The Wall"?', options: ['Rahul Dravid', 'Sachin Tendulkar', 'VVS Laxman', 'Anil Kumble'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'What is the maximum number of overs in an ODI match per team?', options: ['50', '40', '60', '45'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'In which city is the Wankhede Stadium located?', options: ['Mumbai', 'Delhi', 'Chennai', 'Pune'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: 'Who was the first Indian captain to win a Test series in Australia?', options: ['Virat Kohli', 'Anil Kumble', 'MS Dhoni', 'Sourav Ganguly'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'hard',   question: 'Which team won the inaugural IPL in 2008?', options: ['Rajasthan Royals', 'Mumbai Indians', 'Chennai Super Kings', 'Delhi Daredevils'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: "What is Sachin Tendulkar's jersey number?", options: ['10', '7', '18', '11'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Who hit the winning six in the 2011 World Cup final?', options: ['MS Dhoni', 'Virat Kohli', 'Yuvraj Singh', 'Suresh Raina'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'easy',   question: 'Which country does Jasprit Bumrah represent?', options: ['India', 'Pakistan', 'Sri Lanka', 'Bangladesh'], correctIdx: 0 },
  { category: 'cricket', difficulty: 'medium', question: 'What is the name of the fielding position behind the batsman?', options: ['Wicket-keeper', 'Mid-on', 'Slip', 'Fine Leg'], correctIdx: 0 },
  // TDC-unique Cricket
  { category: 'cricket', difficulty: 'easy',   question: "Who hit the famous 'Desert Storm' innings against Australia?", options: ['Sachin Tendulkar', 'Rahul Dravid', 'Sourav Ganguly', 'Virender Sehwag'], correctIdx: 0 },

  // ─── SCIENCE ──────────────────────────────────────────────────────────────
  { category: 'science', difficulty: 'easy',   question: 'What is the chemical symbol for water?', options: ['H₂O', 'CO₂', 'NaCl', 'O₂'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'How many planets are in our solar system?', options: ['8', '9', '7', '10'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'What is the speed of light (approx) in km/s?', options: ['300,000', '150,000', '450,000', '100,000'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'Which gas do plants absorb during photosynthesis?', options: ['Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the powerhouse of the cell?', options: ['Mitochondria', 'Nucleus', 'Ribosome', 'Chloroplast'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the atomic number of hydrogen?', options: ['1', '2', '0', '8'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'Which planet is closest to the Sun?', options: ['Mercury', 'Venus', 'Earth', 'Mars'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the chemical symbol for gold?', options: ['Au', 'Ag', 'Gd', 'Go'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'How many bones are in an adult human body?', options: ['206', '208', '200', '212'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What force keeps planets in orbit around the Sun?', options: ['Gravity', 'Magnetism', 'Friction', 'Electrostatic force'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the boiling point of water at sea level?', options: ['100°C', '90°C', '80°C', '120°C'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'Which is the largest planet in our solar system?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: "What is the most abundant gas in Earth's atmosphere?", options: ['Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'DNA stands for?', options: ['Deoxyribonucleic Acid', 'Dioxynuclear Acid', 'Dinuclear Acid', 'Deoxynuclear Amino'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the unit of electric current?', options: ['Ampere', 'Volt', 'Watt', 'Ohm'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'Which planet is known as the Red Planet?', options: ['Mars', 'Jupiter', 'Venus', 'Saturn'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the chemical symbol for iron?', options: ['Fe', 'Ir', 'In', 'Fr'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'What type of energy does the Sun primarily produce?', options: ['Nuclear fusion energy', 'Nuclear fission energy', 'Chemical energy', 'Kinetic energy'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'How many chambers does a human heart have?', options: ['4', '2', '3', '6'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the SI unit of force?', options: ['Newton', 'Joule', 'Pascal', 'Watt'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'Which organ produces insulin in the human body?', options: ['Pancreas', 'Liver', 'Kidney', 'Spleen'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'What is the speed of sound in air (approx) in m/s?', options: ['343', '300', '200', '400'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'Which vitamin is produced by the body in sunlight?', options: ['Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the chemical symbol for sodium?', options: ['Na', 'So', 'Sd', 'Sn'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'How many chromosomes do humans normally have?', options: ['46', '48', '44', '23'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'What is the hardest natural substance on Earth?', options: ['Diamond', 'Quartz', 'Topaz', 'Corundum'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'The study of stars and galaxies is called?', options: ['Astronomy', 'Astrology', 'Astrophysics', 'Cosmology'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'What is the smallest unit of matter?', options: ['Atom', 'Molecule', 'Electron', 'Quark'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: 'Which blood type is called the "universal donor"?', options: ['O negative', 'AB positive', 'A positive', 'B negative'], correctIdx: 0 },
  { category: 'science', difficulty: 'medium', question: "What is the formula for Newton's second law of motion?", options: ['F = ma', 'E = mc²', 'P = mv', 'W = Fd'], correctIdx: 0 },
  { category: 'science', difficulty: 'hard',   question: 'Which element has the highest melting point?', options: ['Tungsten', 'Iron', 'Carbon', 'Platinum'], correctIdx: 0 },
  { category: 'science', difficulty: 'hard',   question: 'What is the approximate age of the Earth?', options: ['4.5 billion years', '13.8 billion years', '1 billion years', '6000 years'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the pH of pure water?', options: ['7', '0', '14', '5'], correctIdx: 0 },
  { category: 'science', difficulty: 'hard',   question: 'Which planet has the most moons?', options: ['Saturn', 'Jupiter', 'Uranus', 'Neptune'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What does CPU stand for?', options: ['Central Processing Unit', 'Computer Processing Unit', 'Core Processing Unit', 'Central Peripheral Unit'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'Light travels in a?', options: ['Straight line', 'Curved path', 'Zigzag path', 'Wave pattern only'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'How many teeth does an adult human have (including wisdom teeth)?', options: ['32', '28', '30', '34'], correctIdx: 0 },
  { category: 'science', difficulty: 'easy',   question: 'What is the chemical formula for table salt?', options: ['NaCl', 'KCl', 'CaCl₂', 'MgCl₂'], correctIdx: 0 },

  // ─── FOOD & DAILY LIFE ────────────────────────────────────────────────────
  { category: 'food', difficulty: 'easy',   question: 'What is the main ingredient in idli?', options: ['Rice', 'Wheat', 'Maize', 'Barley'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'Which drink is often called "chai"?', options: ['Tea', 'Coffee', 'Milk', 'Lassi'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'What is paneer made from?', options: ['Milk', 'Soy', 'Wheat', 'Rice'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'Which grain is used to make roti?', options: ['Wheat', 'Rice', 'Maize', 'Bajra'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'What is the main spice that gives biryani its colour?', options: ['Saffron', 'Turmeric', 'Cumin', 'Coriander'], correctIdx: 0 },
  { category: 'food', difficulty: 'medium', question: 'Which state is famous for dosa?', options: ['Tamil Nadu', 'Kerala', 'Karnataka', 'Andhra Pradesh'], correctIdx: 0 },
  { category: 'food', difficulty: 'medium', question: 'What is jalebi made of?', options: ['Maida and sugar syrup', 'Rice flour', 'Besan', 'Wheat'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'Which fruit is used to make aamras?', options: ['Mango', 'Banana', 'Papaya', 'Guava'], correctIdx: 0 },
  { category: 'food', difficulty: 'medium', question: 'What is the main ingredient of suji halwa?', options: ['Semolina', 'Wheat', 'Rice', 'Besan'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'Which city is famous for vada pav?', options: ['Mumbai', 'Delhi', 'Pune', 'Nagpur'], correctIdx: 0 },
  { category: 'food', difficulty: 'hard',   question: 'What is "sarson da saag" made from?', options: ['Mustard leaves', 'Spinach', 'Fenugreek', 'Bathua'], correctIdx: 0 },
  { category: 'food', difficulty: 'medium', question: 'Which state is known for dhokla?', options: ['Gujarat', 'Rajasthan', 'Maharashtra', 'Madhya Pradesh'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'What is lassi?', options: ['Yogurt drink', 'Milk shake', 'Juice', 'Tea'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'Which vegetables make aloo gobi?', options: ['Potato and cauliflower', 'Peas', 'Brinjal', 'Okra'], correctIdx: 0 },
  { category: 'food', difficulty: 'medium', question: 'What is upma made from?', options: ['Semolina', 'Rice', 'Wheat', 'Oats'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'Which sweet originated in West Bengal?', options: ['Rasgulla', 'Gulab jamun', 'Jalebi', 'Ladoo'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'What is samosa usually filled with?', options: ['Potato and peas', 'Paneer', 'Meat', 'Cheese'], correctIdx: 0 },
  { category: 'food', difficulty: 'hard',   question: 'Which rice is traditionally used for Hyderabadi biryani?', options: ['Basmati', 'Sona Masoori', 'Ponni', 'Jeerakasala'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'What is the main ingredient of kheer?', options: ['Rice and milk', 'Wheat', 'Vermicelli', 'Semolina'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'Which leaf is used to wrap paan?', options: ['Betel', 'Banana', 'Mango', 'Tulsi'], correctIdx: 0 },
  { category: 'food', difficulty: 'medium', question: 'Which state is famous for the pongal dish?', options: ['Tamil Nadu', 'Kerala', 'Andhra Pradesh', 'Karnataka'], correctIdx: 0 },
  { category: 'food', difficulty: 'hard',   question: 'What is "bisi bele bath"?', options: ['A rice dish from Karnataka', 'A Gujarati thali', 'A Bengali sweet', 'A Punjabi curry'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'What is chaat?', options: ['Savory snack', 'Sweet', 'Drink', 'Main course'], correctIdx: 0 },
  { category: 'food', difficulty: 'medium', question: 'Which nut is used in kaju katli?', options: ['Cashew', 'Almond', 'Pistachio', 'Walnut'], correctIdx: 0 },
  { category: 'food', difficulty: 'easy',   question: 'What is "pav" in pav bhaji?', options: ['Bread roll', 'Rice', 'Roti', 'Bun'], correctIdx: 0 },

  // ─── MODERN INDIA ─────────────────────────────────────────────────────────
  { category: 'modern', difficulty: 'easy',   question: 'Which app is commonly used for UPI payments?', options: ['PhonePe', 'WhatsApp', 'Instagram', 'Twitter'], correctIdx: 0 },
  { category: 'modern', difficulty: 'easy',   question: 'Who founded Reliance Industries?', options: ['Dhirubhai Ambani', 'Mukesh Ambani', 'Anil Ambani', 'Ratan Tata'], correctIdx: 0 },
  { category: 'modern', difficulty: 'easy',   question: 'When was Aadhaar launched?', options: ['2009', '2010', '2011', '2012'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Which scheme provides free LPG connections to rural families?', options: ['Ujjwala', 'Ayushman', 'PM Awas', 'Jan Dhan'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Who founded Infosys?', options: ['N.R. Narayana Murthy', 'Azim Premji', 'Ratan Tata', 'Anil Ambani'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Which Indian state got the first metro rail?', options: ['Kolkata', 'Delhi', 'Mumbai', 'Chennai'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'What does ONDC stand for?', options: ['Open Network for Digital Commerce', 'Online National Digital Channel', 'Open National Data Centre', 'Other'], correctIdx: 0 },
  { category: 'modern', difficulty: 'hard',   question: 'In which year did India launch its first satellite (Aryabhata)?', options: ['1975', '1980', '1972', '1983'], correctIdx: 0 },
  { category: 'modern', difficulty: 'hard',   question: 'Who is the founder of Zomato?', options: ['Deepinder Goyal', 'Bhavish Aggarwal', 'Vijay Shekhar Sharma', 'Kunal Bahl'], correctIdx: 0 },
  { category: 'modern', difficulty: 'easy',   question: 'Which company owns Jio?', options: ['Reliance', 'Airtel', 'Vodafone', 'BSNL'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Which city hosts the Indian F1 Grand Prix circuit?', options: ['Greater Noida', 'Mumbai', 'Bangalore', 'Hyderabad'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Who founded Ola Cabs?', options: ['Bhavish Aggarwal', 'Travis Kalanick', 'Ritesh Agarwal', 'Kunal Bahl'], correctIdx: 0 },
  { category: 'modern', difficulty: 'easy',   question: 'Which year did the Digital India initiative start?', options: ['2015', '2014', '2016', '2017'], correctIdx: 0 },
  { category: 'modern', difficulty: 'hard',   question: 'Who co-founded Flipkart?', options: ['Sachin and Binny Bansal', 'Kunal Bahl', 'Vijay Shekhar Sharma', 'Nandan Nilekani'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Which state launched the first electric vehicle policy in India?', options: ['Delhi', 'Karnataka', 'Maharashtra', 'Gujarat'], correctIdx: 0 },
  { category: 'modern', difficulty: 'easy',   question: 'What does Aadhaar provide to every citizen?', options: ['Unique ID number', 'Bank account', 'Passport', 'Driving license'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Which Indian city has the busiest airport?', options: ['Delhi', 'Mumbai', 'Bangalore', 'Hyderabad'], correctIdx: 0 },
  { category: 'modern', difficulty: 'hard',   question: 'When was GST launched in India?', options: ['2017', '2016', '2018', '2015'], correctIdx: 0 },
  { category: 'modern', difficulty: 'easy',   question: 'Which app is used for train ticket booking?', options: ['IRCTC', 'Paytm', 'MakeMyTrip', 'Goibibo'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Who founded Paytm?', options: ['Vijay Shekhar Sharma', 'Kunal Bahl', 'Ritesh Agarwal', 'Nandan Nilekani'], correctIdx: 0 },
  { category: 'modern', difficulty: 'hard',   question: 'Which Indian state has the highest GDP?', options: ['Maharashtra', 'Tamil Nadu', 'Gujarat', 'Karnataka'], correctIdx: 0 },
  { category: 'modern', difficulty: 'easy',   question: 'What is CoWIN used for?', options: ['Vaccination registration', 'Train booking', 'Aadhaar', 'Banking'], correctIdx: 0 },
  { category: 'modern', difficulty: 'medium', question: 'Which Indian company acquired Jaguar Land Rover?', options: ['Tata Motors', 'Mahindra', 'Maruti', 'Ashok Leyland'], correctIdx: 0 },

  // ─── BRAIN TEASERS ────────────────────────────────────────────────────────
  { category: 'brain', difficulty: 'easy',   question: 'What comes next: 2, 4, 6, 8, ?', options: ['10', '9', '12', '7'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'How many days are in a leap year?', options: ['366', '365', '364', '367'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'What is 15 + 27?', options: ['42', '41', '43', '40'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'Which shape has 6 sides?', options: ['Hexagon', 'Pentagon', 'Octagon', 'Square'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'What is half of 100?', options: ['50', '25', '75', '60'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'What comes next: 1, 1, 2, 3, 5, 8, ?', options: ['13', '11', '12', '14'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'If A=1, B=2, what is C?', options: ['3', '2', '4', '0'], correctIdx: 0 },
  { category: 'brain', difficulty: 'hard',   question: 'How many squares are on a standard chessboard (all sizes)?', options: ['204', '64', '128', '256'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'What is 12 × 12?', options: ['144', '124', '134', '154'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'Which number is the odd one out: 2, 4, 6, 7, 8?', options: ['7', '2', '4', '8'], correctIdx: 0 },
  { category: 'brain', difficulty: 'hard',   question: 'What is the next prime after 17?', options: ['19', '18', '21', '20'], correctIdx: 0 },
  { category: 'brain', difficulty: 'hard',   question: 'If 3x + 6 = 15, what is x?', options: ['3', '2', '4', '5'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'How many faces does a cube have?', options: ['6', '4', '8', '12'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'What is 20% of 80?', options: ['16', '18', '14', '20'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'Which is larger: 0.5 or 0.05?', options: ['0.5', '0.05', 'Same', 'Cannot say'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'What is 2 to the power of 5?', options: ['32', '16', '64', '10'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'How many months have exactly 30 days?', options: ['4', '5', '6', '3'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'What is the square root of 81?', options: ['9', '8', '7', '10'], correctIdx: 0 },
  { category: 'brain', difficulty: 'hard',   question: 'What is 15% of 200?', options: ['30', '25', '35', '20'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'How many hours are in a day?', options: ['24', '12', '48', '20'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'What comes next: 3, 6, 9, 12, ?', options: ['15', '14', '16', '18'], correctIdx: 0 },
  { category: 'brain', difficulty: 'hard',   question: 'How many diagonals does a pentagon have?', options: ['5', '4', '6', '3'], correctIdx: 0 },
  { category: 'brain', difficulty: 'easy',   question: 'What is 7 × 8?', options: ['56', '54', '58', '64'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'Which is NOT a prime number?', options: ['9', '2', '3', '5'], correctIdx: 0 },
  { category: 'brain', difficulty: 'medium', question: 'What is the sum of angles in a triangle?', options: ['180 degrees', '90 degrees', '360 degrees', '270 degrees'], correctIdx: 0 },
]

export const CATEGORY_LABELS = {
  gk:       { en: 'India GK',         hi: 'भारत GK' },
  bollywood:{ en: 'Bollywood',         hi: 'बॉलीवुड' },
  cricket:  { en: 'Cricket',           hi: 'क्रिकेट' },
  science:  { en: 'Science',           hi: 'विज्ञान' },
  food:     { en: 'Food & Daily Life', hi: 'खाना & रोज़मर्रा' },
  modern:   { en: 'Modern India',      hi: 'आधुनिक भारत' },
  brain:    { en: 'Brain Teasers',     hi: 'दिमागी कसरत' },
}

export const CATEGORIES = Object.keys(CATEGORY_LABELS)

/**
 * Get `count` random questions for the given category.
 * Category 'random' picks from all questions.
 */
export function getQuestions(category, count = 10) {
  const pool = category === 'random'
    ? ALL_QUESTIONS
    : ALL_QUESTIONS.filter(q => q.category === category)
  return shuffle(pool).slice(0, count)
}
