export const dcStrings = {
  en: {
    title: 'Dumb Charades',
    teamSetup: 'Team Setup',
    howManyTeams: 'How many teams?',
    teamName: 'Team name',
    next: 'Next →',
    pickCategories: 'Pick Categories',
    difficulty: 'Difficulty',
    settings: 'Settings',
    timer: 'Timer',
    startGame: 'Start Game',
    yourTurn: 'Your Turn!',
    ready: 'READY?',
    tapToStart: 'Start Turn',
    correct: '✓ CORRECT',
    roundEnd: 'Turn Over!',
    gameEnd: 'Game Over!',
    winner: 'WINNER! 🏆',
    tied: "It's a TIE! 🤝",
    playAgain: 'Play Again',
    home: 'Home',
    round: 'Round',
    of: 'of',
    seconds: 's',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    selectAtLeastOne: 'Pick at least one category!',
    unstoppableBadge: '🔥 Unstoppable Team',
    // New scoring model
    winPoints: 'Points to Win',
    customMovies: 'Custom Movies (optional)',
    customMoviesPlaceholder: 'One movie per line…',
    // Actor prep phase
    actorPrepTitle: 'Act This Movie!',
    replaceWord: 'Replace',
    replacementsLeft: 'left',
    readyToAct: 'Ready to Act!',
    yourMovieIs: 'Your movie:',
    prepTimeLeft: 'Prep time',
    // Turn result
    correctGuess: 'Guessed correctly! No points change.',
    timerExpiredMsg: 'Time up! Opponent gets +1 point.',
    nextTurn: 'Next Turn →',
    pointsTo: 'Point goes to',
    // Online
    waitingForSetup: 'Waiting for host to set up the game…',
    teamActing: 'is acting!',
    guesserRole: 'Watch and guess the movie!',
    winPointsTarget: 'First to',
    winsAt: 'points wins',
    // Online setup
    teamAssignment: 'Assign Teams',
    teamA: 'Team A',
    teamB: 'Team B',
    actor: 'Actor',
    guesser: 'Guesser',
    startOnlineGame: 'Start Game →',
    assignAllPlayers: 'Assign all players to a team first',
    needOneActorPerTeam: 'Each team needs exactly one actor',
    // Game over
    scoreLabel: 'Score',
    // End game / dev mode
    endGame: 'End Game',
    confirmEndGame: 'End game now?',
    yesEnd: 'Yes, end',
    devMode: 'Dev mode',
    skipPrep: 'Skip Prep',
    waitingForPlayer2: 'Waiting for 2nd player…',
    youAreTeam: 'You are:',
  },
  hi: {
    title: 'डम्ब शरेड्स',
    teamSetup: 'टीम सेटअप',
    howManyTeams: 'कितनी टीमें?',
    teamName: 'टीम का नाम',
    next: 'आगे →',
    pickCategories: 'कैटेगरी चुनें',
    difficulty: 'मुश्किल',
    settings: 'सेटिंग्स',
    timer: 'टाइमर',
    startGame: 'खेल शुरू करें',
    yourTurn: 'आपकी बारी!',
    ready: 'तैयार?',
    tapToStart: 'बारी शुरू करें',
    correct: '✓ सही',
    roundEnd: 'बारी खत्म!',
    gameEnd: 'खेल खत्म!',
    winner: 'विजेता! 🏆',
    tied: 'बराबर! 🤝',
    playAgain: 'फिर खेलें',
    home: 'होम',
    round: 'राउंड',
    of: '/',
    seconds: 'सेकंड',
    easy: 'आसान',
    medium: 'मध्यम',
    hard: 'मुश्किल',
    selectAtLeastOne: 'कम से कम एक चुनें!',
    unstoppableBadge: '🔥 अजेय टीम',
    // New scoring model
    winPoints: 'जीतने के लिए पॉइंट',
    customMovies: 'कस्टम फ़िल्में (वैकल्पिक)',
    customMoviesPlaceholder: 'एक फ़िल्म प्रति लाइन…',
    // Actor prep phase
    actorPrepTitle: 'यह फ़िल्म एक्ट करें!',
    replaceWord: 'बदलें',
    replacementsLeft: 'बचे',
    readyToAct: 'एक्ट के लिए तैयार!',
    yourMovieIs: 'आपकी फ़िल्म:',
    prepTimeLeft: 'तैयारी का समय',
    // Turn result
    correctGuess: 'सही अनुमान! कोई पॉइंट नहीं बदला।',
    timerExpiredMsg: 'समय खत्म! विरोधी को +1 पॉइंट।',
    nextTurn: 'अगली बारी →',
    pointsTo: 'पॉइंट मिला',
    // Online
    waitingForSetup: 'होस्ट के खेल सेट करने का इंतज़ार…',
    teamActing: 'एक्ट कर रही है!',
    guesserRole: 'देखो और फ़िल्म का अनुमान लगाओ!',
    winPointsTarget: 'पहले',
    winsAt: 'पॉइंट पर जीत',
    // Online setup
    teamAssignment: 'टीम असाइन करें',
    teamA: 'टीम A',
    teamB: 'टीम B',
    actor: 'एक्टर',
    guesser: 'अनुमानकर्ता',
    startOnlineGame: 'खेल शुरू करें →',
    assignAllPlayers: 'पहले सभी खिलाड़ियों को टीम में रखें',
    needOneActorPerTeam: 'प्रत्येक टीम में एक एक्टर होना चाहिए',
    // Game over
    scoreLabel: 'स्कोर',
    // End game / dev mode
    endGame: 'खेल खत्म करें',
    confirmEndGame: 'अभी खेल खत्म करें?',
    yesEnd: 'हाँ, खत्म करो',
    devMode: 'डेव मोड',
    skipPrep: 'तैयारी छोड़ें',
    waitingForPlayer2: 'दूसरे खिलाड़ी का इंतज़ार…',
    youAreTeam: 'आप हैं:',
  }
}

export function useDCStrings(lang) {
  const strings = dcStrings[lang] ?? dcStrings.en
  return (key) => strings[key] ?? key
}
