export const dcStrings = {
  en: {
    title: 'Dumb Charades',
    teamSetup: 'Team Setup',
    howManyTeams: 'How many teams?',
    teamName: 'Team name',
    next: 'Next →',
    pickCategories: 'Pick Categories',
    difficulty: 'Difficulty',
    settings: 'Settings',
    timer: 'Timer',
    scoringMode: 'Scoring Mode',
    maxWords: 'Max Words in Time',
    fastestGuess: 'Fastest Guess',
    inputMode: 'Input Mode',
    tap: 'Tap Buttons',
    swipe: 'Swipe',
    volume: 'Volume Keys',
    startGame: 'Start Game',
    yourTurn: 'Your Turn!',
    ready: 'READY?',
    tapToStart: 'Tap to Start',
    correct: '✓ CORRECT',
    pass: '✗ PASS',
    swipeRight: '→ Swipe Right = Correct',
    swipeLeft: '← Swipe Left = Pass',
    volumeUp: '🔊 Vol Up = Correct',
    volumeDown: '🔉 Vol Down = Pass',
    roundEnd: 'Round Over!',
    wordsGuessed: 'Words Guessed',
    wordsPassed: 'Passed',
    score: 'Score',
    nextTeamTurn: "Next Team's Turn →",
    gameEnd: 'Game Over!',
    winner: 'WINNER! 🏆',
    tied: "It's a TIE! 🤝",
    playAgain: 'Play Again',
    home: 'Home',
    round: 'Round',
    of: 'of',
    seconds: 's',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    roundsPerTeam: 'Rounds per Team',
    selectAtLeastOne: 'Pick at least one category!',
    mvpBadge: '🎭 MVP Actor',
    fastRoundBadge: '⚡ Fastest Round',
    unstoppableBadge: '🔥 Unstoppable Team'
  },
  hi: {
    title: 'डम्ब शरेड्स',
    teamSetup: 'टीम सेटअप',
    howManyTeams: 'कितनी टीमें?',
    teamName: 'टीम का नाम',
    next: 'आगे →',
    pickCategories: 'कैटेगरी चुनें',
    difficulty: 'मुश्किल',
    settings: 'सेटिंग्स',
    timer: 'टाइमर',
    scoringMode: 'स्कोरिंग',
    maxWords: 'ज़्यादा शब्द',
    fastestGuess: 'जल्दी अनुमान',
    inputMode: 'इनपुट',
    tap: 'बटन दबाएं',
    swipe: 'स्वाइप करें',
    volume: 'वॉल्यूम बटन',
    startGame: 'खेल शुरू करें',
    yourTurn: 'आपकी बारी!',
    ready: 'तैयार?',
    tapToStart: 'दबाकर शुरू करें',
    correct: '✓ सही',
    pass: '✗ पास',
    swipeRight: '→ दाएं = सही',
    swipeLeft: '← बाएं = पास',
    volumeUp: '🔊 Vol Up = सही',
    volumeDown: '🔉 Vol Down = पास',
    roundEnd: 'राउंड खत्म!',
    wordsGuessed: 'सही शब्द',
    wordsPassed: 'पास',
    score: 'स्कोर',
    nextTeamTurn: 'अगली टीम की बारी →',
    gameEnd: 'खेल खत्म!',
    winner: 'विजेता! 🏆',
    tied: 'बराबर! 🤝',
    playAgain: 'फिर खेलें',
    home: 'होम',
    round: 'राउंड',
    of: '/',
    seconds: 'सेकंड',
    easy: 'आसान',
    medium: 'मध्यम',
    hard: 'मुश्किल',
    roundsPerTeam: 'प्रति टीम राउंड',
    selectAtLeastOne: 'कम से कम एक चुनें!',
    mvpBadge: '🎭 सर्वश्रेष्ठ अभिनेता',
    fastRoundBadge: '⚡ सबसे तेज़ राउंड',
    unstoppableBadge: '🔥 अजेय टीम'
  }
}

export function useDCStrings(lang) {
  const strings = dcStrings[lang] ?? dcStrings.en
  return (key) => strings[key] ?? key
}
