// Each word: { word: string, difficulty: 'easy' | 'medium' | 'hard' }
// difficulty ladder: easy ⊂ medium ⊂ hard (medium pool includes easy words)

const bollywoodMovies = {
  slug: 'bollywood-movies',
  label: { en: 'Bollywood Movies', hi: 'बॉलीवुड फ़िल्में' },
  icon: '🎬',
  words: [
    // Easy (65)
    { word: 'Sholay', difficulty: 'easy' },
    { word: 'DDLJ', difficulty: 'easy' },
    { word: '3 Idiots', difficulty: 'easy' },
    { word: 'PK', difficulty: 'easy' },
    { word: 'Singham', difficulty: 'easy' },
    { word: 'Dhoom', difficulty: 'easy' },
    { word: 'Hera Pheri', difficulty: 'easy' },
    { word: 'Lagaan', difficulty: 'easy' },
    { word: 'Gadar', difficulty: 'easy' },
    { word: 'Krrish', difficulty: 'easy' },
    { word: 'Chennai Express', difficulty: 'easy' },
    { word: 'Bhool Bhulaiyaa', difficulty: 'easy' },
    { word: 'Munna Bhai MBBS', difficulty: 'easy' },
    { word: 'Don', difficulty: 'easy' },
    { word: 'Kabir Singh', difficulty: 'easy' },
    { word: 'Wanted', difficulty: 'easy' },
    { word: 'Ready', difficulty: 'easy' },
    { word: 'Dabangg', difficulty: 'easy' },
    { word: 'Golmaal', difficulty: 'easy' },
    { word: 'Tiger Zinda Hai', difficulty: 'easy' },
    { word: 'Housefull', difficulty: 'easy' },
    { word: 'Dilwale', difficulty: 'easy' },
    { word: 'Baahubali', difficulty: 'easy' },
    { word: 'Pushpa', difficulty: 'easy' },
    { word: 'Shershaah', difficulty: 'easy' },
    { word: 'Jab We Met', difficulty: 'easy' },
    { word: 'Dil Wale', difficulty: 'easy' },
    { word: 'Kaho Na Pyaar Hai', difficulty: 'easy' },
    { word: 'Student of the Year', difficulty: 'easy' },
    { word: 'Kick', difficulty: 'easy' },
    { word: 'Bang Bang', difficulty: 'easy' },
    { word: 'Race', difficulty: 'easy' },
    { word: 'Action Replayy', difficulty: 'easy' },
    { word: 'Ek Tha Tiger', difficulty: 'easy' },
    { word: 'Fan', difficulty: 'easy' },
    { word: 'Bodyguard', difficulty: 'easy' },
    { word: 'Dhamaal', difficulty: 'easy' },
    { word: 'Welcome', difficulty: 'easy' },
    { word: 'Partner', difficulty: 'easy' },
    { word: 'Grand Masti', difficulty: 'easy' },
    { word: 'Fukrey', difficulty: 'easy' },
    { word: 'Bol Bachchan', difficulty: 'easy' },
    { word: 'Son of Sardaar', difficulty: 'easy' },
    { word: 'Tanu Weds Manu', difficulty: 'easy' },
    { word: 'Prem Ratan Dhan Payo', difficulty: 'easy' },
    { word: 'Bajirao Mastani', difficulty: 'easy' },
    { word: 'Padmaavat', difficulty: 'easy' },
    { word: 'Gully Boy', difficulty: 'easy' },
    { word: 'Article 15', difficulty: 'easy' },
    { word: 'War', difficulty: 'easy' },
    { word: 'Tanhaji', difficulty: 'easy' },
    { word: 'Sooryavanshi', difficulty: 'easy' },
    { word: 'Bell Bottom', difficulty: 'easy' },
    { word: 'Atrangi Re', difficulty: 'easy' },
    { word: 'Radhe Shyam', difficulty: 'easy' },
    { word: 'KGF', difficulty: 'easy' },
    { word: 'RRR', difficulty: 'easy' },
    { word: 'Pathaan', difficulty: 'easy' },
    { word: 'Jawan', difficulty: 'easy' },
    { word: 'Animal', difficulty: 'easy' },
    { word: 'Dunki', difficulty: 'easy' },
    { word: 'Tiger 3', difficulty: 'easy' },
    { word: 'Fighter', difficulty: 'easy' },
    { word: 'Kalki 2898 AD', difficulty: 'easy' },
    { word: 'Stree 2', difficulty: 'easy' },
    // Medium (85)
    { word: 'Zindagi Na Milegi Dobara', difficulty: 'medium' },
    { word: 'Bajrangi Bhaijaan', difficulty: 'medium' },
    { word: 'Sultan', difficulty: 'medium' },
    { word: 'Barfi', difficulty: 'medium' },
    { word: 'Dil Chahta Hai', difficulty: 'medium' },
    { word: 'Rockstar', difficulty: 'medium' },
    { word: 'Chhichhore', difficulty: 'medium' },
    { word: 'Uri', difficulty: 'medium' },
    { word: 'Dil Dhadakne Do', difficulty: 'medium' },
    { word: 'Queen', difficulty: 'medium' },
    { word: 'Kal Ho Na Ho', difficulty: 'medium' },
    { word: 'Veer Zaara', difficulty: 'medium' },
    { word: 'Kahaani', difficulty: 'medium' },
    { word: 'Rang De Basanti', difficulty: 'medium' },
    { word: 'Swades', difficulty: 'medium' },
    { word: 'Taare Zameen Par', difficulty: 'medium' },
    { word: 'Dev D', difficulty: 'medium' },
    { word: 'Gangs of Wasseypur', difficulty: 'medium' },
    { word: 'Bhaag Milkha Bhaag', difficulty: 'medium' },
    { word: 'MS Dhoni', difficulty: 'medium' },
    { word: 'Neerja', difficulty: 'medium' },
    { word: 'Pink', difficulty: 'medium' },
    { word: 'Airlift', difficulty: 'medium' },
    { word: 'Stree', difficulty: 'medium' },
    { word: 'Thappad', difficulty: 'medium' },
    { word: 'Tamasha', difficulty: 'medium' },
    { word: 'Raazi', difficulty: 'medium' },
    { word: 'Andhadhun', difficulty: 'medium' },
    { word: 'Kesari', difficulty: 'medium' },
    { word: 'Super 30', difficulty: 'medium' },
    { word: 'Yeh Jawaani Hai Deewani', difficulty: 'medium' },
    { word: 'Kapoor and Sons', difficulty: 'medium' },
    { word: 'Kai Po Che', difficulty: 'medium' },
    { word: 'Gangs of Wasseypur 2', difficulty: 'medium' },
    { word: 'Madaari', difficulty: 'medium' },
    { word: 'Rustom', difficulty: 'medium' },
    { word: 'Wazir', difficulty: 'medium' },
    { word: 'M.S. Dhoni Untold Story', difficulty: 'medium' },
    { word: 'Dangal', difficulty: 'medium' },
    { word: 'Secret Superstar', difficulty: 'medium' },
    { word: 'Thugs of Hindostan', difficulty: 'medium' },
    { word: 'Zero', difficulty: 'medium' },
    { word: 'Simmba', difficulty: 'medium' },
    { word: 'Mission Mangal', difficulty: 'medium' },
    { word: 'Bard of Blood', difficulty: 'medium' },
    { word: 'Guilty', difficulty: 'medium' },
    { word: 'Dil Bechara', difficulty: 'medium' },
    { word: 'Shakuntala Devi', difficulty: 'medium' },
    { word: 'Ludo', difficulty: 'medium' },
    { word: 'Mirzapur', difficulty: 'medium' },
    { word: 'Scam 1992', difficulty: 'medium' },
    { word: 'Maharani', difficulty: 'medium' },
    { word: 'Haseen Dillruba', difficulty: 'medium' },
    { word: 'Sardar Udham', difficulty: 'medium' },
    { word: 'Sherni', difficulty: 'medium' },
    { word: 'Bhuj', difficulty: 'medium' },
    { word: 'Bhoot Police', difficulty: 'medium' },
    { word: 'Bunty Aur Babli 2', difficulty: 'medium' },
    { word: 'Antim', difficulty: 'medium' },
    { word: 'Chandigarh Kare Aashiqui', difficulty: 'medium' },
    { word: 'Gehraiyaan', difficulty: 'medium' },
    { word: 'Badhaai Do', difficulty: 'medium' },
    { word: 'Dhamaka', difficulty: 'medium' },
    { word: 'The Family Man', difficulty: 'medium' },
    { word: 'Panchayat', difficulty: 'medium' },
    { word: 'Aspirants', difficulty: 'medium' },
    { word: 'Rocket Boys', difficulty: 'medium' },
    { word: 'Jai Bhim', difficulty: 'medium' },
    { word: 'Sarpatta Parambarai', difficulty: 'medium' },
    { word: 'Minnal Murali', difficulty: 'medium' },
    { word: 'Shiddat', difficulty: 'medium' },
    { word: 'Lucknow Central', difficulty: 'medium' },
    { word: 'Mardaani', difficulty: 'medium' },
    { word: 'Badla', difficulty: 'medium' },
    { word: 'Bala', difficulty: 'medium' },
    { word: 'Dream Girl', difficulty: 'medium' },
    { word: 'Chhalaang', difficulty: 'medium' },
    { word: 'Toofaan', difficulty: 'medium' },
    { word: 'Pagglait', difficulty: 'medium' },
    { word: 'Mimi', difficulty: 'medium' },
    { word: 'Sardar Ka Grandson', difficulty: 'medium' },
    { word: 'Roohi', difficulty: 'medium' },
    { word: 'Saina', difficulty: 'medium' },
    { word: 'Mumbai Saga', difficulty: 'medium' },
    { word: 'Radhe', difficulty: 'medium' },
    // Hard (55)
    { word: 'Jaane Bhi Do Yaaro', difficulty: 'hard' },
    { word: 'Maqbool', difficulty: 'hard' },
    { word: 'Haider', difficulty: 'hard' },
    { word: 'Talvar', difficulty: 'hard' },
    { word: 'Masaan', difficulty: 'hard' },
    { word: 'Udaan', difficulty: 'hard' },
    { word: 'Shahid', difficulty: 'hard' },
    { word: 'Newton', difficulty: 'hard' },
    { word: 'Trapped', difficulty: 'hard' },
    { word: 'Tumbbad', difficulty: 'hard' },
    { word: 'Lootera', difficulty: 'hard' },
    { word: 'Paan Singh Tomar', difficulty: 'hard' },
    { word: 'A Wednesday', difficulty: 'hard' },
    { word: 'Dhobi Ghat', difficulty: 'hard' },
    { word: 'Pyaasa', difficulty: 'hard' },
    { word: 'Mughal-E-Azam', difficulty: 'hard' },
    { word: 'Sahib Bibi Aur Ghulam', difficulty: 'hard' },
    { word: 'Do Ankhen Barah Haath', difficulty: 'hard' },
    { word: 'Kaun', difficulty: 'hard' },
    { word: 'Gulaal', difficulty: 'hard' },
    { word: 'Ship of Theseus', difficulty: 'hard' },
    { word: 'Titli', difficulty: 'hard' },
    { word: 'Court', difficulty: 'hard' },
    { word: 'Visaranai', difficulty: 'hard' },
    { word: 'Kammatipaadam', difficulty: 'hard' },
    { word: 'Lucia', difficulty: 'hard' },
    { word: 'Ondu Motteya Kathe', difficulty: 'hard' },
    { word: 'Ulidavaru Kandanthe', difficulty: 'hard' },
    { word: 'Peepli Live', difficulty: 'hard' },
    { word: 'Aamir', difficulty: 'hard' },
    { word: 'Gulabi Talkies', difficulty: 'hard' },
    { word: 'Oye Lucky', difficulty: 'hard' },
    { word: 'Bheja Fry', difficulty: 'hard' },
    { word: 'Khosla Ka Ghosla', difficulty: 'hard' },
    { word: 'Do Dooni Chaar', difficulty: 'hard' },
    { word: 'Tere Bin Laden', difficulty: 'hard' },
    { word: 'Band Baaja Baaraat', difficulty: 'hard' },
    { word: 'Vicky Donor', difficulty: 'hard' },
    { word: 'Kai Po Che', difficulty: 'hard' },
    { word: 'The Lunchbox', difficulty: 'hard' },
    { word: 'Dedh Ishqiya', difficulty: 'hard' },
    { word: 'Highway', difficulty: 'hard' },
    { word: 'Finding Fanny', difficulty: 'hard' },
    { word: 'Titoo MBA', difficulty: 'hard' },
    { word: 'NH10', difficulty: 'hard' },
    { word: 'Manjhi', difficulty: 'hard' },
    { word: 'Parched', difficulty: 'hard' },
    { word: 'Aligarh', difficulty: 'hard' },
    { word: 'Mirzya', difficulty: 'hard' },
    { word: 'Mukkabaaz', difficulty: 'hard' },
    { word: 'Laila Majnu', difficulty: 'hard' },
    { word: 'Sonchiriya', difficulty: 'hard' },
    { word: 'Photograph', difficulty: 'hard' },
    { word: 'Bombay Rose', difficulty: 'hard' },
    { word: 'Choked', difficulty: 'hard' },
  ]
}

const bollywoodActors = {
  slug: 'bollywood-actors',
  label: { en: 'Bollywood Stars', hi: 'बॉलीवुड सितारे' },
  icon: '⭐',
  words: [
    // Easy (25)
    { word: 'Shah Rukh Khan', difficulty: 'easy' },
    { word: 'Salman Khan', difficulty: 'easy' },
    { word: 'Aamir Khan', difficulty: 'easy' },
    { word: 'Akshay Kumar', difficulty: 'easy' },
    { word: 'Amitabh Bachchan', difficulty: 'easy' },
    { word: 'Deepika Padukone', difficulty: 'easy' },
    { word: 'Priyanka Chopra', difficulty: 'easy' },
    { word: 'Katrina Kaif', difficulty: 'easy' },
    { word: 'Kareena Kapoor', difficulty: 'easy' },
    { word: 'Hrithik Roshan', difficulty: 'easy' },
    { word: 'Ranbir Kapoor', difficulty: 'easy' },
    { word: 'Ranveer Singh', difficulty: 'easy' },
    { word: 'Alia Bhatt', difficulty: 'easy' },
    { word: 'Tiger Shroff', difficulty: 'easy' },
    { word: 'Sanjay Dutt', difficulty: 'easy' },
    { word: 'Ajay Devgn', difficulty: 'easy' },
    { word: 'Govinda', difficulty: 'easy' },
    { word: 'Anil Kapoor', difficulty: 'easy' },
    { word: 'Madhuri Dixit', difficulty: 'easy' },
    { word: 'Kajol', difficulty: 'easy' },
    { word: 'Aishwarya Rai', difficulty: 'easy' },
    { word: 'Sunny Deol', difficulty: 'easy' },
    { word: 'John Abraham', difficulty: 'easy' },
    { word: 'Varun Dhawan', difficulty: 'easy' },
    { word: 'Shraddha Kapoor', difficulty: 'easy' },
    // Medium (35)
    { word: 'Nawazuddin Siddiqui', difficulty: 'medium' },
    { word: 'Irrfan Khan', difficulty: 'medium' },
    { word: 'Rajkummar Rao', difficulty: 'medium' },
    { word: 'Ayushmann Khurrana', difficulty: 'medium' },
    { word: 'Vicky Kaushal', difficulty: 'medium' },
    { word: 'Kartik Aaryan', difficulty: 'medium' },
    { word: 'Taapsee Pannu', difficulty: 'medium' },
    { word: 'Kangana Ranaut', difficulty: 'medium' },
    { word: 'Vidya Balan', difficulty: 'medium' },
    { word: 'Dimple Kapadia', difficulty: 'medium' },
    { word: 'Rekha', difficulty: 'medium' },
    { word: 'Hema Malini', difficulty: 'medium' },
    { word: 'Dharmendra', difficulty: 'medium' },
    { word: 'Mithun Chakraborty', difficulty: 'medium' },
    { word: 'Jackie Shroff', difficulty: 'medium' },
    { word: 'Nora Fatehi', difficulty: 'medium' },
    { word: 'Kriti Sanon', difficulty: 'medium' },
    { word: 'Disha Patani', difficulty: 'medium' },
    { word: 'Bhumi Pednekar', difficulty: 'medium' },
    { word: 'Sanya Malhotra', difficulty: 'medium' },
    { word: 'Yami Gautam', difficulty: 'medium' },
    { word: 'Sonakshi Sinha', difficulty: 'medium' },
    { word: 'Prabhas', difficulty: 'medium' },
    { word: 'Allu Arjun', difficulty: 'medium' },
    { word: 'Vijay Deverakonda', difficulty: 'medium' },
    { word: 'Ram Charan', difficulty: 'medium' },
    { word: 'Jr NTR', difficulty: 'medium' },
    { word: 'Mahesh Babu', difficulty: 'medium' },
    { word: 'Vijay', difficulty: 'medium' },
    { word: 'Rajinikanth', difficulty: 'medium' },
    { word: 'Radhika Apte', difficulty: 'medium' },
    { word: 'Fatima Sana Shaikh', difficulty: 'medium' },
    { word: 'Tamannaah Bhatia', difficulty: 'medium' },
    { word: 'Konkona Sen Sharma', difficulty: 'medium' },
    { word: 'Arjun Kapoor', difficulty: 'medium' },
    // Hard (20)
    { word: 'Pankaj Tripathi', difficulty: 'hard' },
    { word: 'Manoj Bajpayee', difficulty: 'hard' },
    { word: 'Naseeruddin Shah', difficulty: 'hard' },
    { word: 'Om Puri', difficulty: 'hard' },
    { word: 'Shabana Azmi', difficulty: 'hard' },
    { word: 'Nana Patekar', difficulty: 'hard' },
    { word: 'Anupam Kher', difficulty: 'hard' },
    { word: 'Paresh Rawal', difficulty: 'hard' },
    { word: 'Tabu', difficulty: 'hard' },
    { word: 'Swara Bhaskar', difficulty: 'hard' },
    { word: 'Richa Chadha', difficulty: 'hard' },
    { word: 'Kalki Koechlin', difficulty: 'hard' },
    { word: 'Seema Pahwa', difficulty: 'hard' },
    { word: 'Ratna Pathak Shah', difficulty: 'hard' },
    { word: 'Boman Irani', difficulty: 'hard' },
    { word: 'Emraan Hashmi', difficulty: 'hard' },
    { word: 'Arjun Rampal', difficulty: 'hard' },
    { word: 'Gulshan Grover', difficulty: 'hard' },
    { word: 'Amrish Puri', difficulty: 'hard' },
    { word: 'Danny Denzongpa', difficulty: 'hard' }
  ]
}

const everydayObjects = {
  slug: 'everyday-objects',
  label: { en: 'Everyday Objects', hi: 'रोज़मर्रा की चीज़ें' },
  icon: '🏠',
  words: [
    // Easy (25)
    { word: 'Chair', difficulty: 'easy' },
    { word: 'Table', difficulty: 'easy' },
    { word: 'Phone', difficulty: 'easy' },
    { word: 'Book', difficulty: 'easy' },
    { word: 'Bag', difficulty: 'easy' },
    { word: 'Bottle', difficulty: 'easy' },
    { word: 'Pencil', difficulty: 'easy' },
    { word: 'Spoon', difficulty: 'easy' },
    { word: 'Cup', difficulty: 'easy' },
    { word: 'Plate', difficulty: 'easy' },
    { word: 'Bed', difficulty: 'easy' },
    { word: 'Fan', difficulty: 'easy' },
    { word: 'Lamp', difficulty: 'easy' },
    { word: 'Mirror', difficulty: 'easy' },
    { word: 'Shoes', difficulty: 'easy' },
    { word: 'Watch', difficulty: 'easy' },
    { word: 'Key', difficulty: 'easy' },
    { word: 'Pen', difficulty: 'easy' },
    { word: 'Umbrella', difficulty: 'easy' },
    { word: 'Cycle', difficulty: 'easy' },
    { word: 'Ball', difficulty: 'easy' },
    { word: 'Helmet', difficulty: 'easy' },
    { word: 'Towel', difficulty: 'easy' },
    { word: 'Pillow', difficulty: 'easy' },
    { word: 'Comb', difficulty: 'easy' },
    // Medium (35)
    { word: 'Pressure Cooker', difficulty: 'medium' },
    { word: 'Remote Control', difficulty: 'medium' },
    { word: 'Refrigerator', difficulty: 'medium' },
    { word: 'Alarm Clock', difficulty: 'medium' },
    { word: 'Scissors', difficulty: 'medium' },
    { word: 'Screwdriver', difficulty: 'medium' },
    { word: 'Hammer', difficulty: 'medium' },
    { word: 'Torch', difficulty: 'medium' },
    { word: 'Compass', difficulty: 'medium' },
    { word: 'Toaster', difficulty: 'medium' },
    { word: 'Blender', difficulty: 'medium' },
    { word: 'Iron', difficulty: 'medium' },
    { word: 'Sewing Machine', difficulty: 'medium' },
    { word: 'Safety Pin', difficulty: 'medium' },
    { word: 'Stapler', difficulty: 'medium' },
    { word: 'Ruler', difficulty: 'medium' },
    { word: 'Eraser', difficulty: 'medium' },
    { word: 'Sharpener', difficulty: 'medium' },
    { word: 'Magnet', difficulty: 'medium' },
    { word: 'Battery', difficulty: 'medium' },
    { word: 'Charger', difficulty: 'medium' },
    { word: 'Earphones', difficulty: 'medium' },
    { word: 'Camera', difficulty: 'medium' },
    { word: 'Selfie Stick', difficulty: 'medium' },
    { word: 'Power Bank', difficulty: 'medium' },
    { word: 'Keyboard', difficulty: 'medium' },
    { word: 'Microscope', difficulty: 'medium' },
    { word: 'Telescope', difficulty: 'medium' },
    { word: 'Binoculars', difficulty: 'medium' },
    { word: 'Knitting Needle', difficulty: 'medium' },
    { word: 'Tape Measure', difficulty: 'medium' },
    { word: 'Whistle', difficulty: 'medium' },
    { word: 'Padlock', difficulty: 'medium' },
    { word: 'Matchbox', difficulty: 'medium' },
    { word: 'Dustpan', difficulty: 'medium' },
    // Hard (20)
    { word: 'Theodolite', difficulty: 'hard' },
    { word: 'Oscilloscope', difficulty: 'hard' },
    { word: 'Centrifuge', difficulty: 'hard' },
    { word: 'Spectrometer', difficulty: 'hard' },
    { word: 'Barometer', difficulty: 'hard' },
    { word: 'Altimeter', difficulty: 'hard' },
    { word: 'Chronometer', difficulty: 'hard' },
    { word: 'Sextant', difficulty: 'hard' },
    { word: 'Gyroscope', difficulty: 'hard' },
    { word: 'Stethoscope', difficulty: 'hard' },
    { word: 'Sphygmomanometer', difficulty: 'hard' },
    { word: 'Defibrillator', difficulty: 'hard' },
    { word: 'Periscope', difficulty: 'hard' },
    { word: 'Kaleidoscope', difficulty: 'hard' },
    { word: 'Pantograph', difficulty: 'hard' },
    { word: 'Soldering Iron', difficulty: 'hard' },
    { word: '3D Printer', difficulty: 'hard' },
    { word: 'Drone', difficulty: 'hard' },
    { word: 'Lie Detector', difficulty: 'hard' },
    { word: 'Night Vision Goggles', difficulty: 'hard' }
  ]
}

const animals = {
  slug: 'animals',
  label: { en: 'Animals', hi: 'जानवर' },
  icon: '🦁',
  words: [
    // Easy (25)
    { word: 'Dog', difficulty: 'easy' },
    { word: 'Cat', difficulty: 'easy' },
    { word: 'Lion', difficulty: 'easy' },
    { word: 'Tiger', difficulty: 'easy' },
    { word: 'Elephant', difficulty: 'easy' },
    { word: 'Monkey', difficulty: 'easy' },
    { word: 'Horse', difficulty: 'easy' },
    { word: 'Cow', difficulty: 'easy' },
    { word: 'Buffalo', difficulty: 'easy' },
    { word: 'Goat', difficulty: 'easy' },
    { word: 'Rabbit', difficulty: 'easy' },
    { word: 'Duck', difficulty: 'easy' },
    { word: 'Parrot', difficulty: 'easy' },
    { word: 'Snake', difficulty: 'easy' },
    { word: 'Frog', difficulty: 'easy' },
    { word: 'Turtle', difficulty: 'easy' },
    { word: 'Crocodile', difficulty: 'easy' },
    { word: 'Giraffe', difficulty: 'easy' },
    { word: 'Zebra', difficulty: 'easy' },
    { word: 'Bear', difficulty: 'easy' },
    { word: 'Deer', difficulty: 'easy' },
    { word: 'Camel', difficulty: 'easy' },
    { word: 'Fish', difficulty: 'easy' },
    { word: 'Hen', difficulty: 'easy' },
    { word: 'Sheep', difficulty: 'easy' },
    // Medium (35)
    { word: 'Cheetah', difficulty: 'medium' },
    { word: 'Leopard', difficulty: 'medium' },
    { word: 'Jaguar', difficulty: 'medium' },
    { word: 'Hyena', difficulty: 'medium' },
    { word: 'Jackal', difficulty: 'medium' },
    { word: 'Wolf', difficulty: 'medium' },
    { word: 'Fox', difficulty: 'medium' },
    { word: 'Otter', difficulty: 'medium' },
    { word: 'Squirrel', difficulty: 'medium' },
    { word: 'Hedgehog', difficulty: 'medium' },
    { word: 'Porcupine', difficulty: 'medium' },
    { word: 'Kangaroo', difficulty: 'medium' },
    { word: 'Koala', difficulty: 'medium' },
    { word: 'Flamingo', difficulty: 'medium' },
    { word: 'Penguin', difficulty: 'medium' },
    { word: 'Ostrich', difficulty: 'medium' },
    { word: 'Peacock', difficulty: 'medium' },
    { word: 'Toucan', difficulty: 'medium' },
    { word: 'Owl', difficulty: 'medium' },
    { word: 'Eagle', difficulty: 'medium' },
    { word: 'Vulture', difficulty: 'medium' },
    { word: 'Pelican', difficulty: 'medium' },
    { word: 'Swan', difficulty: 'medium' },
    { word: 'Octopus', difficulty: 'medium' },
    { word: 'Jellyfish', difficulty: 'medium' },
    { word: 'Seahorse', difficulty: 'medium' },
    { word: 'Dolphin', difficulty: 'medium' },
    { word: 'Whale', difficulty: 'medium' },
    { word: 'Gorilla', difficulty: 'medium' },
    { word: 'Panda', difficulty: 'medium' },
    { word: 'Polar Bear', difficulty: 'medium' },
    { word: 'Chimpanzee', difficulty: 'medium' },
    { word: 'Rhinoceros', difficulty: 'medium' },
    { word: 'Hippopotamus', difficulty: 'medium' },
    { word: 'Komodo Dragon', difficulty: 'medium' },
    // Hard (20)
    { word: 'Axolotl', difficulty: 'hard' },
    { word: 'Pangolin', difficulty: 'hard' },
    { word: 'Tapir', difficulty: 'hard' },
    { word: 'Capybara', difficulty: 'hard' },
    { word: 'Okapi', difficulty: 'hard' },
    { word: 'Binturong', difficulty: 'hard' },
    { word: 'Narwhal', difficulty: 'hard' },
    { word: 'Dugong', difficulty: 'hard' },
    { word: 'Manatee', difficulty: 'hard' },
    { word: 'Tarsier', difficulty: 'hard' },
    { word: 'Mandrill', difficulty: 'hard' },
    { word: 'Proboscis Monkey', difficulty: 'hard' },
    { word: 'Gharial', difficulty: 'hard' },
    { word: 'Tuatara', difficulty: 'hard' },
    { word: 'Kakapo', difficulty: 'hard' },
    { word: 'Quokka', difficulty: 'hard' },
    { word: 'Platypus', difficulty: 'hard' },
    { word: 'Aye-aye', difficulty: 'hard' },
    { word: 'Saiga', difficulty: 'hard' },
    { word: 'Fossa', difficulty: 'hard' }
  ]
}

const professions = {
  slug: 'professions',
  label: { en: 'Professions', hi: 'पेशे' },
  icon: '👷',
  words: [
    // Easy (25)
    { word: 'Doctor', difficulty: 'easy' },
    { word: 'Teacher', difficulty: 'easy' },
    { word: 'Police', difficulty: 'easy' },
    { word: 'Driver', difficulty: 'easy' },
    { word: 'Cook', difficulty: 'easy' },
    { word: 'Farmer', difficulty: 'easy' },
    { word: 'Soldier', difficulty: 'easy' },
    { word: 'Nurse', difficulty: 'easy' },
    { word: 'Carpenter', difficulty: 'easy' },
    { word: 'Tailor', difficulty: 'easy' },
    { word: 'Barber', difficulty: 'easy' },
    { word: 'Painter', difficulty: 'easy' },
    { word: 'Fisherman', difficulty: 'easy' },
    { word: 'Gardener', difficulty: 'easy' },
    { word: 'Plumber', difficulty: 'easy' },
    { word: 'Electrician', difficulty: 'easy' },
    { word: 'Pilot', difficulty: 'easy' },
    { word: 'Actor', difficulty: 'easy' },
    { word: 'Singer', difficulty: 'easy' },
    { word: 'Dancer', difficulty: 'easy' },
    { word: 'Shopkeeper', difficulty: 'easy' },
    { word: 'Postman', difficulty: 'easy' },
    { word: 'Security Guard', difficulty: 'easy' },
    { word: 'Banker', difficulty: 'easy' },
    { word: 'Journalist', difficulty: 'easy' },
    // Medium (35)
    { word: 'Architect', difficulty: 'medium' },
    { word: 'Accountant', difficulty: 'medium' },
    { word: 'Lawyer', difficulty: 'medium' },
    { word: 'Judge', difficulty: 'medium' },
    { word: 'Photographer', difficulty: 'medium' },
    { word: 'Chef', difficulty: 'medium' },
    { word: 'Nutritionist', difficulty: 'medium' },
    { word: 'Physiotherapist', difficulty: 'medium' },
    { word: 'Pharmacist', difficulty: 'medium' },
    { word: 'Veterinarian', difficulty: 'medium' },
    { word: 'Dentist', difficulty: 'medium' },
    { word: 'Surgeon', difficulty: 'medium' },
    { word: 'Psychiatrist', difficulty: 'medium' },
    { word: 'Psychologist', difficulty: 'medium' },
    { word: 'Stock Broker', difficulty: 'medium' },
    { word: 'Real Estate Agent', difficulty: 'medium' },
    { word: 'Interior Designer', difficulty: 'medium' },
    { word: 'Fashion Designer', difficulty: 'medium' },
    { word: 'Jeweller', difficulty: 'medium' },
    { word: 'Blacksmith', difficulty: 'medium' },
    { word: 'Welder', difficulty: 'medium' },
    { word: 'Mason', difficulty: 'medium' },
    { word: 'Contractor', difficulty: 'medium' },
    { word: 'Meteorologist', difficulty: 'medium' },
    { word: 'Astronomer', difficulty: 'medium' },
    { word: 'Zoologist', difficulty: 'medium' },
    { word: 'Botanist', difficulty: 'medium' },
    { word: 'Historian', difficulty: 'medium' },
    { word: 'Librarian', difficulty: 'medium' },
    { word: 'Social Worker', difficulty: 'medium' },
    { word: 'Firefighter', difficulty: 'medium' },
    { word: 'Lifeguard', difficulty: 'medium' },
    { word: 'Referee', difficulty: 'medium' },
    { word: 'Coach', difficulty: 'medium' },
    { word: 'Optician', difficulty: 'medium' },
    // Hard (20)
    { word: 'Actuary', difficulty: 'hard' },
    { word: 'Epidemiologist', difficulty: 'hard' },
    { word: 'Forensic Scientist', difficulty: 'hard' },
    { word: 'Criminologist', difficulty: 'hard' },
    { word: 'Anthropologist', difficulty: 'hard' },
    { word: 'Archaeologist', difficulty: 'hard' },
    { word: 'Palaeontologist', difficulty: 'hard' },
    { word: 'Volcanologist', difficulty: 'hard' },
    { word: 'Seismologist', difficulty: 'hard' },
    { word: 'Oceanographer', difficulty: 'hard' },
    { word: 'Toxicologist', difficulty: 'hard' },
    { word: 'Cryptographer', difficulty: 'hard' },
    { word: 'Biostatistician', difficulty: 'hard' },
    { word: 'Ethnobotanist', difficulty: 'hard' },
    { word: 'Lepidopterist', difficulty: 'hard' },
    { word: 'Herpetologist', difficulty: 'hard' },
    { word: 'Malacologist', difficulty: 'hard' },
    { word: 'Arachnologist', difficulty: 'hard' },
    { word: 'Radiobiologist', difficulty: 'hard' },
    { word: 'Computational Linguist', difficulty: 'hard' }
  ]
}

export const wordpacks = [
  bollywoodMovies,
  bollywoodActors,
  everydayObjects,
  animals,
  professions
]

/**
 * Build a word pool from selected categories and difficulty.
 * @param {string[]} categorySlugs - which packs to include
 * @param {string} difficulty - 'easy' | 'medium' | 'hard'
 * @param {string[]} customWords - extra words always included (any difficulty)
 */
export function buildWordQueue(categorySlugs, difficulty, customWords = []) {
  const diffPool = {
    easy: ['easy'],
    medium: ['easy', 'medium'],
    hard: ['easy', 'medium', 'hard']
  }
  const allowed = new Set(diffPool[difficulty] ?? ['easy'])

  const packWords = wordpacks
    .filter(pack => categorySlugs.includes(pack.slug))
    .flatMap(pack => pack.words.filter(w => allowed.has(w.difficulty)).map(w => w.word))

  // Merge custom words (always included, deduplicated)
  const all = [...packWords, ...customWords]
  return [...new Set(all)]
}
