// Dumb Charades word packs.
// difficulty ladder: easy ⊂ medium ⊂ hard (medium pool includes easy, hard includes all)
// bollywood_movies entries have a hints object: { cast, year, genre, tagline }
// All other categories use { word, difficulty } only.

const bollywood_movies = {
  label: 'Bollywood Movies',
  emoji: '🎬',
  words: [
    // ── Easy (63) ─────────────────────────────────────────────────────────────
    { word: 'Sholay', difficulty: 'easy',
      hints: { cast: 'Amitabh Bachchan, Dharmendra, Hema Malini', year: '1975', genre: 'Action / Adventure', tagline: 'Kitne aadmi the?' } },
    { word: 'DDLJ', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan, Kajol', year: '1995', genre: 'Romance', tagline: 'Come, fall in love' } },
    { word: '3 Idiots', difficulty: 'easy',
      hints: { cast: 'Aamir Khan, R. Madhavan, Sharman Joshi', year: '2009', genre: 'Comedy / Drama', tagline: 'Aal Izz Well' } },
    { word: 'PK', difficulty: 'easy',
      hints: { cast: 'Aamir Khan, Anushka Sharma', year: '2014', genre: 'Comedy / Drama', tagline: 'An alien in search of God' } },
    { word: 'Singham', difficulty: 'easy',
      hints: { cast: 'Ajay Devgn, Kajal Aggarwal', year: '2011', genre: 'Action', tagline: 'Aata majhi satakli!' } },
    { word: 'Dhoom', difficulty: 'easy',
      hints: { cast: 'Abhishek Bachchan, John Abraham, Uday Chopra', year: '2004', genre: 'Action / Thriller', tagline: 'Bikes, heists and style' } },
    { word: 'Hera Pheri', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Suniel Shetty, Paresh Rawal', year: '2000', genre: 'Comedy', tagline: 'Babu bhaiya!' } },
    { word: 'Lagaan', difficulty: 'easy',
      hints: { cast: 'Aamir Khan, Gracy Singh', year: '2001', genre: 'Drama / Sports', tagline: 'Cricket against the British' } },
    { word: 'Gadar', difficulty: 'easy',
      hints: { cast: 'Sunny Deol, Ameesha Patel', year: '2001', genre: 'Action / Drama', tagline: 'Partition-era love story — Tara Singh' } },
    { word: 'Krrish', difficulty: 'easy',
      hints: { cast: 'Hrithik Roshan, Priyanka Chopra', year: '2006', genre: 'Action / Sci-Fi', tagline: "India's first superhero" } },
    { word: 'Chennai Express', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan, Deepika Padukone', year: '2013', genre: 'Comedy / Action', tagline: 'Train journey to South India' } },
    { word: 'Bhool Bhulaiyaa', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Vidya Balan', year: '2007', genre: 'Horror / Comedy', tagline: 'Bhool mat jaana...' } },
    { word: 'Munna Bhai MBBS', difficulty: 'easy',
      hints: { cast: 'Sanjay Dutt, Arshad Warsi', year: '2003', genre: 'Comedy / Drama', tagline: 'A gangster goes to medical college' } },
    { word: 'Don', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan, Priyanka Chopra', year: '2006', genre: 'Action / Thriller', tagline: 'Don ko pakadna mushkil hi nahin, namumkin hai' } },
    { word: 'Kabir Singh', difficulty: 'easy',
      hints: { cast: 'Shahid Kapoor, Kiara Advani', year: '2019', genre: 'Romance / Drama', tagline: 'A doctor consumed by love and self-destruction' } },
    { word: 'Wanted', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Ayesha Takia', year: '2009', genre: 'Action', tagline: 'Being bad is good' } },
    { word: 'Ready', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Asin', year: '2011', genre: 'Comedy / Action', tagline: 'A mistaken identity comedy caper' } },
    { word: 'Dabangg', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Sonakshi Sinha', year: '2010', genre: 'Action / Comedy', tagline: 'Hud hud Dabangg' } },
    { word: 'Golmaal', difficulty: 'easy',
      hints: { cast: 'Ajay Devgn, Arshad Warsi, Shreyas Talpade', year: '2006', genre: 'Comedy', tagline: 'It is fun time!' } },
    { word: 'Tiger Zinda Hai', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Katrina Kaif', year: '2017', genre: 'Action / Spy', tagline: 'Tiger abhi zinda hai' } },
    { word: 'Housefull', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Deepika Padukone, Riteish Deshmukh', year: '2010', genre: 'Comedy', tagline: 'Full paisa vasool comedy' } },
    { word: 'Dilwale', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan, Kajol, Varun Dhawan', year: '2015', genre: 'Action / Romance', tagline: 'Gerua' } },
    { word: 'Baahubali', difficulty: 'easy',
      hints: { cast: 'Prabhas, Rana Daggubati, Tamannah Bhatia', year: '2015', genre: 'Action / Epic', tagline: 'Kattappa ne Baahubali ko kyun maara?' } },
    { word: 'Pushpa', difficulty: 'easy',
      hints: { cast: 'Allu Arjun, Rashmika Mandanna', year: '2021', genre: 'Action / Crime', tagline: 'Pushpa naam sunke flowers samjhe kya?' } },
    { word: 'Shershaah', difficulty: 'easy',
      hints: { cast: 'Sidharth Malhotra, Kiara Advani', year: '2021', genre: 'War / Biopic', tagline: 'Captain Vikram Batra — Yeh Dil Maange More' } },
    { word: 'Jab We Met', difficulty: 'easy',
      hints: { cast: 'Shahid Kapoor, Kareena Kapoor', year: '2007', genre: 'Romantic Comedy', tagline: 'Main apni favourite hoon!' } },
    { word: 'Kaho Na Pyaar Hai', difficulty: 'easy',
      hints: { cast: 'Hrithik Roshan, Ameesha Patel', year: '2000', genre: 'Romance', tagline: "Hrithik Roshan's debut — double role" } },
    { word: 'Student of the Year', difficulty: 'easy',
      hints: { cast: 'Alia Bhatt, Sidharth Malhotra, Varun Dhawan', year: '2012', genre: 'Romance / Drama', tagline: 'College love triangle' } },
    { word: 'Kick', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Jacqueline Fernandez', year: '2014', genre: 'Action / Comedy', tagline: "Devil in the game" } },
    { word: 'Bang Bang', difficulty: 'easy',
      hints: { cast: 'Hrithik Roshan, Katrina Kaif', year: '2014', genre: 'Action / Thriller', tagline: 'Bang Bang tu hi meri rani' } },
    { word: 'Race', difficulty: 'easy',
      hints: { cast: 'Saif Ali Khan, Akshaye Khanna, Bipasha Basu', year: '2008', genre: 'Action / Thriller', tagline: 'Get ready for the race' } },
    { word: 'Action Replayy', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Aishwarya Rai', year: '2010', genre: 'Comedy / Sci-Fi', tagline: 'A son time-travels to fix his parents marriage' } },
    { word: 'Ek Tha Tiger', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Katrina Kaif', year: '2012', genre: 'Action / Spy', tagline: 'A spy falls for the enemy' } },
    { word: 'Fan', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan', year: '2016', genre: 'Thriller / Drama', tagline: 'A superstar and his obsessive lookalike fan' } },
    { word: 'Bodyguard', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Kareena Kapoor', year: '2011', genre: 'Action / Romance', tagline: 'Dil diyan gallan' } },
    { word: 'Dhamaal', difficulty: 'easy',
      hints: { cast: 'Arshad Warsi, Riteish Deshmukh, Javed Jaffrey', year: '2007', genre: 'Comedy', tagline: 'Four idiots hunt hidden treasure' } },
    { word: 'Welcome', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Nana Patekar, Anil Kapoor', year: '2007', genre: 'Comedy', tagline: 'Don family comedy of errors' } },
    { word: 'Partner', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Govinda', year: '2007', genre: 'Romantic Comedy', tagline: 'Love guru helps a shy businessman' } },
    { word: 'Grand Masti', difficulty: 'easy',
      hints: { cast: 'Riteish Deshmukh, Vivek Oberoi, Aftab Shivdasani', year: '2013', genre: 'Adult Comedy', tagline: 'Three friends at a college reunion' } },
    { word: 'Fukrey', difficulty: 'easy',
      hints: { cast: 'Pulkit Samrat, Ali Fazal, Varun Sharma', year: '2013', genre: 'Comedy', tagline: 'Jugaad hai yaar' } },
    { word: 'Bol Bachchan', difficulty: 'easy',
      hints: { cast: 'Ajay Devgn, Abhishek Bachchan', year: '2012', genre: 'Comedy', tagline: 'One lie leads to a hundred more' } },
    { word: 'Son of Sardaar', difficulty: 'easy',
      hints: { cast: 'Ajay Devgn, Sonakshi Sinha', year: '2012', genre: 'Action / Comedy', tagline: 'Oye Babaji — revenge in Punjab' } },
    { word: 'Tanu Weds Manu', difficulty: 'easy',
      hints: { cast: 'R. Madhavan, Kangana Ranaut', year: '2011', genre: 'Romantic Comedy', tagline: 'A wild girl and a proper doctor' } },
    { word: 'Prem Ratan Dhan Payo', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Sonam Kapoor', year: '2015', genre: 'Romance / Drama', tagline: 'A prince swapped with his lookalike' } },
    { word: 'Bajirao Mastani', difficulty: 'easy',
      hints: { cast: 'Ranveer Singh, Deepika Padukone, Priyanka Chopra', year: '2015', genre: 'Historical / Romance', tagline: 'Deewani Mastani' } },
    { word: 'Padmaavat', difficulty: 'easy',
      hints: { cast: 'Deepika Padukone, Ranveer Singh, Shahid Kapoor', year: '2018', genre: 'Historical / Drama', tagline: 'Ghoomar — queen of Mewar' } },
    { word: 'Gully Boy', difficulty: 'easy',
      hints: { cast: 'Ranveer Singh, Alia Bhatt', year: '2019', genre: 'Drama / Music', tagline: 'Apna Time Aayega' } },
    { word: 'War', difficulty: 'easy',
      hints: { cast: 'Hrithik Roshan, Tiger Shroff', year: '2019', genre: 'Action / Thriller', tagline: 'Agent vs his own mentor' } },
    { word: 'Tanhaji', difficulty: 'easy',
      hints: { cast: 'Ajay Devgn, Saif Ali Khan, Kajol', year: '2020', genre: 'Historical / Action', tagline: 'Maratha warrior recaptures Kondhana fort' } },
    { word: 'Sooryavanshi', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Katrina Kaif', year: '2021', genre: 'Action / Thriller', tagline: 'Aala re aala Sooryavanshi aala' } },
    { word: 'Bell Bottom', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Vaani Kapoor', year: '2021', genre: 'Spy / Thriller', tagline: '1984 hijack rescue mission' } },
    { word: 'Atrangi Re', difficulty: 'easy',
      hints: { cast: 'Akshay Kumar, Sara Ali Khan, Dhanush', year: '2021', genre: 'Romance / Fantasy', tagline: 'Unusual love triangle' } },
    { word: 'KGF', difficulty: 'easy',
      hints: { cast: 'Yash, Srinidhi Shetty', year: '2018', genre: 'Action / Crime', tagline: 'Power. Gold. Blood.' } },
    { word: 'RRR', difficulty: 'easy',
      hints: { cast: 'Ram Charan, Jr NTR, Alia Bhatt', year: '2022', genre: 'Action / Historical', tagline: 'Naatu Naatu' } },
    { word: 'Pathaan', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan, Deepika Padukone', year: '2023', genre: 'Action / Thriller', tagline: 'Besharam Rang' } },
    { word: 'Jawan', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan, Nayanthara', year: '2023', genre: 'Action', tagline: 'A man robs a train to expose corruption' } },
    { word: 'Animal', difficulty: 'easy',
      hints: { cast: 'Ranbir Kapoor, Anil Kapoor, Rashmika Mandanna', year: '2023', genre: 'Action / Thriller', tagline: 'A man driven by rage — obsession with his father' } },
    { word: 'Dunki', difficulty: 'easy',
      hints: { cast: 'Shah Rukh Khan, Taapsee Pannu', year: '2023', genre: 'Comedy / Drama', tagline: 'Illegal immigration — donkey flight' } },
    { word: 'Tiger 3', difficulty: 'easy',
      hints: { cast: 'Salman Khan, Katrina Kaif', year: '2023', genre: 'Action / Spy', tagline: 'Tiger hi raaj karega' } },
    { word: 'Fighter', difficulty: 'easy',
      hints: { cast: 'Hrithik Roshan, Deepika Padukone', year: '2024', genre: 'Action / War', tagline: 'Indian Air Force vs terror' } },
    { word: 'Kalki 2898 AD', difficulty: 'easy',
      hints: { cast: 'Prabhas, Deepika Padukone, Amitabh Bachchan', year: '2024', genre: 'Action / Sci-Fi', tagline: 'The final avatar in a dystopian future' } },
    { word: 'Stree 2', difficulty: 'easy',
      hints: { cast: 'Rajkummar Rao, Shraddha Kapoor', year: '2024', genre: 'Horror / Comedy', tagline: 'Aao kabhi Chanderi mein' } },
    { word: 'Singham Returns', difficulty: 'easy',
      hints: { cast: 'Ajay Devgn, Kareena Kapoor', year: '2014', genre: 'Action', tagline: 'Singham is back — Aata majhi satakli' } },

    // ── Medium (75) ───────────────────────────────────────────────────────────
    { word: 'Zindagi Na Milegi Dobara', difficulty: 'medium',
      hints: { cast: 'Hrithik Roshan, Farhan Akhtar, Abhay Deol', year: '2011', genre: 'Drama / Comedy', tagline: 'Three friends on a road trip across Spain' } },
    { word: 'Bajrangi Bhaijaan', difficulty: 'medium',
      hints: { cast: 'Salman Khan, Harshaali Malhotra, Kareena Kapoor', year: '2015', genre: 'Drama / Adventure', tagline: 'A man returns a mute Pakistani girl home' } },
    { word: 'Sultan', difficulty: 'medium',
      hints: { cast: 'Salman Khan, Anushka Sharma', year: '2016', genre: 'Drama / Sports', tagline: 'A wrestling champion makes a comeback for love' } },
    { word: 'Barfi', difficulty: 'medium',
      hints: { cast: 'Ranbir Kapoor, Priyanka Chopra, Ileana DCruz', year: '2012', genre: 'Comedy / Drama', tagline: 'A deaf-mute man and his love stories' } },
    { word: 'Dil Chahta Hai', difficulty: 'medium',
      hints: { cast: 'Aamir Khan, Saif Ali Khan, Akshaye Khanna', year: '2001', genre: 'Comedy / Drama', tagline: 'Friendship never ends — Goa trip' } },
    { word: 'Rockstar', difficulty: 'medium',
      hints: { cast: 'Ranbir Kapoor, Nargis Fakhri', year: '2011', genre: 'Drama / Music', tagline: 'Jo Bhi Main' } },
    { word: 'Chhichhore', difficulty: 'medium',
      hints: { cast: 'Sushant Singh Rajput, Shraddha Kapoor', year: '2019', genre: 'Comedy / Drama', tagline: 'IIT college reunion — losers can win' } },
    { word: 'Uri', difficulty: 'medium',
      hints: { cast: 'Vicky Kaushal, Yami Gautam', year: '2019', genre: 'Military / Action', tagline: "How's the josh?" } },
    { word: 'Dil Dhadakne Do', difficulty: 'medium',
      hints: { cast: 'Ranveer Singh, Priyanka Chopra, Anil Kapoor', year: '2015', genre: 'Drama / Comedy', tagline: 'Family secrets surface on a Mediterranean cruise' } },
    { word: 'Queen', difficulty: 'medium',
      hints: { cast: 'Kangana Ranaut, Lisa Haydon', year: '2014', genre: 'Drama / Comedy', tagline: 'A woman goes on her honeymoon alone' } },
    { word: 'Kal Ho Na Ho', difficulty: 'medium',
      hints: { cast: 'Shah Rukh Khan, Preity Zinta, Saif Ali Khan', year: '2003', genre: 'Romance / Drama', tagline: 'A man lives life fully knowing his time is short' } },
    { word: 'Veer Zaara', difficulty: 'medium',
      hints: { cast: 'Shah Rukh Khan, Preity Zinta', year: '2004', genre: 'Romance / Drama', tagline: 'Love across India and Pakistan' } },
    { word: 'Kahaani', difficulty: 'medium',
      hints: { cast: 'Vidya Balan, Parambrata Chattopadhyay', year: '2012', genre: 'Thriller / Mystery', tagline: 'A pregnant woman searches for her missing husband in Kolkata' } },
    { word: 'Rang De Basanti', difficulty: 'medium',
      hints: { cast: 'Aamir Khan, Siddharth, Soha Ali Khan', year: '2006', genre: 'Drama / Political', tagline: 'No country is perfect, you have to make it' } },
    { word: 'Swades', difficulty: 'medium',
      hints: { cast: 'Shah Rukh Khan, Gayatri Joshi', year: '2004', genre: 'Drama', tagline: 'NASA scientist returns to rural India' } },
    { word: 'Taare Zameen Par', difficulty: 'medium',
      hints: { cast: 'Aamir Khan, Darsheel Safary', year: '2007', genre: 'Drama', tagline: 'Har bachcha khaas hota hai — dyslexia story' } },
    { word: 'Dev D', difficulty: 'medium',
      hints: { cast: 'Abhay Deol, Mahie Gill, Kalki Koechlin', year: '2009', genre: 'Drama / Musical', tagline: 'Modern retelling of Devdas' } },
    { word: 'Gangs of Wasseypur', difficulty: 'medium',
      hints: { cast: 'Manoj Bajpayee, Nawazuddin Siddiqui', year: '2012', genre: 'Crime / Drama', tagline: 'Beta, tumse na ho payega — coal mafia saga' } },
    { word: 'Bhaag Milkha Bhaag', difficulty: 'medium',
      hints: { cast: 'Farhan Akhtar, Sonam Kapoor', year: '2013', genre: 'Sports / Biopic', tagline: 'Bhaag Milkha bhaag — The Flying Sikh' } },
    { word: 'MS Dhoni', difficulty: 'medium',
      hints: { cast: 'Sushant Singh Rajput, Kiara Advani', year: '2016', genre: 'Biopic / Drama', tagline: 'Maahi way — from Ranchi to World Cup captain' } },
    { word: 'Neerja', difficulty: 'medium',
      hints: { cast: 'Sonam Kapoor, Shabana Azmi', year: '2016', genre: 'Biopic / Thriller', tagline: 'Flight attendant hero of Pan Am 73 hijack' } },
    { word: 'Pink', difficulty: 'medium',
      hints: { cast: 'Amitabh Bachchan, Taapsee Pannu', year: '2016', genre: 'Drama / Legal', tagline: 'No means no' } },
    { word: 'Airlift', difficulty: 'medium',
      hints: { cast: 'Akshay Kumar, Nimrat Kaur', year: '2016', genre: 'Drama / Historical', tagline: 'Evacuation of Indians from Kuwait in 1990' } },
    { word: 'Stree', difficulty: 'medium',
      hints: { cast: 'Rajkummar Rao, Shraddha Kapoor', year: '2018', genre: 'Horror / Comedy', tagline: 'O Stree kal aana — Chanderi town mystery' } },
    { word: 'Thappad', difficulty: 'medium',
      hints: { cast: 'Taapsee Pannu, Pavail Gulati', year: '2020', genre: 'Drama', tagline: 'Ek thappad — bas itna sa sawaal' } },
    { word: 'Tamasha', difficulty: 'medium',
      hints: { cast: 'Ranbir Kapoor, Deepika Padukone', year: '2015', genre: 'Drama / Romance', tagline: 'A man trapped in a life not his own' } },
    { word: 'Raazi', difficulty: 'medium',
      hints: { cast: 'Alia Bhatt, Vicky Kaushal', year: '2018', genre: 'Spy / Thriller', tagline: 'An Indian girl spies inside a Pakistani family' } },
    { word: 'Andhadhun', difficulty: 'medium',
      hints: { cast: 'Ayushmann Khurrana, Tabu, Radhika Apte', year: '2018', genre: 'Thriller / Black Comedy', tagline: 'A pianist who fakes blindness witnesses a murder' } },
    { word: 'Kesari', difficulty: 'medium',
      hints: { cast: 'Akshay Kumar, Parineeti Chopra', year: '2019', genre: 'War / Historical', tagline: 'Battle of Saragarhi — 21 Sikhs vs 10,000' } },
    { word: 'Super 30', difficulty: 'medium',
      hints: { cast: 'Hrithik Roshan, Mrunal Thakur', year: '2019', genre: 'Biopic / Drama', tagline: 'Anand Kumar coaches 30 underprivileged students for IIT' } },
    { word: 'Yeh Jawaani Hai Deewani', difficulty: 'medium',
      hints: { cast: 'Ranbir Kapoor, Deepika Padukone', year: '2013', genre: 'Romance / Drama', tagline: 'Kabira — wanderlust vs love' } },
    { word: 'Kapoor and Sons', difficulty: 'medium',
      hints: { cast: 'Fawad Khan, Sidharth Malhotra, Alia Bhatt', year: '2016', genre: 'Family Drama', tagline: 'A dysfunctional family reunites' } },
    { word: 'Kai Po Che', difficulty: 'medium',
      hints: { cast: 'Sushant Singh Rajput, Rajkummar Rao, Amit Sadh', year: '2013', genre: 'Drama / Sports', tagline: 'Three friends and a kite shop — Gujarat riots backdrop' } },
    { word: 'Rustom', difficulty: 'medium',
      hints: { cast: 'Akshay Kumar, Ileana DCruz', year: '2016', genre: 'Thriller / Drama', tagline: 'Based on the KM Nanavati case' } },
    { word: 'Wazir', difficulty: 'medium',
      hints: { cast: 'Amitabh Bachchan, Farhan Akhtar', year: '2016', genre: 'Thriller / Drama', tagline: 'Chess grandmaster and a cop — revenge thriller' } },
    { word: 'Dangal', difficulty: 'medium',
      hints: { cast: 'Aamir Khan, Fatima Sana Shaikh', year: '2016', genre: 'Sports / Biopic', tagline: 'Mahavir Phogat trains daughters for wrestling gold' } },
    { word: 'Secret Superstar', difficulty: 'medium',
      hints: { cast: 'Zaira Wasim, Aamir Khan', year: '2017', genre: 'Drama / Music', tagline: 'A girl sings secretly on YouTube' } },
    { word: 'Simmba', difficulty: 'medium',
      hints: { cast: 'Ranveer Singh, Sara Ali Khan', year: '2018', genre: 'Action / Comedy', tagline: 'Aila re aillaa — a corrupt cop reforms' } },
    { word: 'Mission Mangal', difficulty: 'medium',
      hints: { cast: 'Akshay Kumar, Vidya Balan', year: '2019', genre: 'Drama / Sci-Fi', tagline: 'ISRO Mars Orbiter Mission — team of scientists' } },
    { word: 'Dil Bechara', difficulty: 'medium',
      hints: { cast: 'Sushant Singh Rajput, Sanjana Sanghi', year: '2020', genre: 'Romance / Drama', tagline: 'Based on The Fault in Our Stars — cancer love story' } },
    { word: 'Shakuntala Devi', difficulty: 'medium',
      hints: { cast: 'Vidya Balan, Sanya Malhotra', year: '2020', genre: 'Biopic / Drama', tagline: 'The human computer' } },
    { word: 'Ludo', difficulty: 'medium',
      hints: { cast: 'Abhishek Bachchan, Rajkummar Rao, Aditya Roy Kapur', year: '2020', genre: 'Black Comedy / Thriller', tagline: 'Four stories connected by fate — like a board game' } },
    { word: 'Haseen Dillruba', difficulty: 'medium',
      hints: { cast: 'Taapsee Pannu, Vikrant Massey', year: '2021', genre: 'Thriller / Romance', tagline: 'A crime fiction obsessed woman and a murder mystery' } },
    { word: 'Sardar Udham', difficulty: 'medium',
      hints: { cast: 'Vicky Kaushal', year: '2021', genre: 'Biopic / Historical', tagline: 'Jallianwala Bagh avenger — hunts Michael ODwyer' } },
    { word: 'Bhuj', difficulty: 'medium',
      hints: { cast: 'Ajay Devgn, Sonakshi Sinha', year: '2021', genre: 'War / Action', tagline: '1971 Indo-Pak war — IAF runway rebuilt by villagers' } },
    { word: 'Antim', difficulty: 'medium',
      hints: { cast: 'Salman Khan, Aayush Sharma', year: '2021', genre: 'Action / Crime', tagline: 'Cop vs gangster — the final truth' } },
    { word: 'Chandigarh Kare Aashiqui', difficulty: 'medium',
      hints: { cast: 'Ayushmann Khurrana, Vaani Kapoor', year: '2021', genre: 'Romance / Drama', tagline: 'A bodybuilder falls for a Zumba instructor with a secret' } },
    { word: 'Gehraiyaan', difficulty: 'medium',
      hints: { cast: 'Deepika Padukone, Siddhant Chaturvedi, Ananya Panday', year: '2022', genre: 'Drama / Thriller', tagline: 'Complicated relationships and betrayal' } },
    { word: 'Badhaai Do', difficulty: 'medium',
      hints: { cast: 'Rajkummar Rao, Bhumi Pednekar', year: '2022', genre: 'Drama / Comedy', tagline: 'A gay man and a lesbian marry for cover' } },
    { word: 'Dhamaka', difficulty: 'medium',
      hints: { cast: 'Kartik Aaryan, Mrunal Thakur', year: '2021', genre: 'Thriller / Drama', tagline: 'A TV journalist covers a live bomb threat' } },
    { word: 'Shiddat', difficulty: 'medium',
      hints: { cast: 'Sunny Kaushal, Radhika Madan', year: '2021', genre: 'Romance / Drama', tagline: 'Love so intense it crosses borders' } },
    { word: 'Mardaani', difficulty: 'medium',
      hints: { cast: 'Rani Mukerji', year: '2014', genre: 'Action / Crime', tagline: 'A cop takes on a child trafficking ring' } },
    { word: 'Badla', difficulty: 'medium',
      hints: { cast: 'Amitabh Bachchan, Taapsee Pannu', year: '2019', genre: 'Thriller / Mystery', tagline: 'A woman accused of murder hires a sharp lawyer' } },
    { word: 'Bala', difficulty: 'medium',
      hints: { cast: 'Ayushmann Khurrana, Bhumi Pednekar, Yami Gautam', year: '2019', genre: 'Comedy / Drama', tagline: 'A prematurely bald man and his insecurities' } },
    { word: 'Dream Girl', difficulty: 'medium',
      hints: { cast: 'Ayushmann Khurrana, Nushrratt Bharuccha', year: '2019', genre: 'Comedy', tagline: 'A man fools everyone with his female phone voice' } },
    { word: 'Toofaan', difficulty: 'medium',
      hints: { cast: 'Farhan Akhtar, Mrunal Thakur', year: '2021', genre: 'Sports / Drama', tagline: 'A street thug becomes a national boxing champion' } },
    { word: 'Mimi', difficulty: 'medium',
      hints: { cast: 'Kriti Sanon, Pankaj Tripathi', year: '2021', genre: 'Drama / Comedy', tagline: 'A surrogate mother keeps the baby against all odds' } },
    { word: 'Roohi', difficulty: 'medium',
      hints: { cast: 'Rajkummar Rao, Janhvi Kapoor, Varun Sharma', year: '2021', genre: 'Horror / Comedy', tagline: 'A witch spirit that steals brides' } },
    { word: 'Saina', difficulty: 'medium',
      hints: { cast: 'Parineeti Chopra', year: '2021', genre: 'Sports / Biopic', tagline: 'Rise of Saina Nehwal to world badminton champion' } },
    { word: 'Mumbai Saga', difficulty: 'medium',
      hints: { cast: 'John Abraham, Emraan Hashmi', year: '2021', genre: 'Crime / Action', tagline: 'Mumbai underworld gangster saga' } },
    { word: 'Radhe', difficulty: 'medium',
      hints: { cast: 'Salman Khan, Disha Patani', year: '2021', genre: 'Action', tagline: 'Your most wanted bhai' } },
    { word: 'Article 15', difficulty: 'medium',
      hints: { cast: 'Ayushmann Khurrana, Sayani Gupta', year: '2019', genre: 'Drama / Crime', tagline: 'A cop investigates caste-based violence in UP' } },
    { word: 'Gangs of Wasseypur 2', difficulty: 'medium',
      hints: { cast: 'Nawazuddin Siddiqui, Huma Qureshi', year: '2012', genre: 'Crime / Drama', tagline: 'Faizal Khan completes the family vendetta' } },
    { word: 'Thugs of Hindostan', difficulty: 'medium',
      hints: { cast: 'Amitabh Bachchan, Aamir Khan, Katrina Kaif', year: '2018', genre: 'Action / Adventure', tagline: 'A thug hired to infiltrate freedom fighters' } },
    { word: 'Zero', difficulty: 'medium',
      hints: { cast: 'Shah Rukh Khan, Anushka Sharma, Katrina Kaif', year: '2018', genre: 'Drama / Romance', tagline: 'Love story of a vertically challenged man' } },
    { word: 'Lucknow Central', difficulty: 'medium',
      hints: { cast: 'Farhan Akhtar, Diana Penty', year: '2017', genre: 'Drama / Music', tagline: 'Prisoners form a band to escape jail' } },
    { word: 'Chhalaang', difficulty: 'medium',
      hints: { cast: 'Rajkummar Rao, Nushrratt Bharuccha', year: '2020', genre: 'Sports / Comedy', tagline: 'A lazy PTI teacher finds his purpose' } },
    { word: 'Sardar Ka Grandson', difficulty: 'medium',
      hints: { cast: 'Arjun Kapoor, Neena Gupta', year: '2021', genre: 'Comedy / Drama', tagline: 'A grandson tries to bring his grandmother house from Pakistan' } },
    { word: 'Pagglait', difficulty: 'medium',
      hints: { cast: 'Sanya Malhotra', year: '2021', genre: 'Drama / Comedy', tagline: 'A widow who cannot cry discovers herself' } },
    { word: 'Jai Bhim', difficulty: 'medium',
      hints: { cast: 'Suriya, Lijomol Jose', year: '2021', genre: 'Legal / Drama', tagline: 'A lawyer fights for tribal justice — based on true events' } },
    { word: 'Sarpatta Parambarai', difficulty: 'medium',
      hints: { cast: 'Arya, Dushara Vijayan', year: '2021', genre: 'Sports / Drama', tagline: 'Tamil boxing clan rivalry in 1970s Madras' } },
    { word: 'Minnal Murali', difficulty: 'medium',
      hints: { cast: 'Tovino Thomas', year: '2021', genre: 'Superhero / Comedy', tagline: 'Kerala tailor gets lightning superpowers' } },
    { word: 'Bhoot Police', difficulty: 'medium',
      hints: { cast: 'Saif Ali Khan, Arjun Kapoor', year: '2021', genre: 'Horror / Comedy', tagline: 'Two brothers who exorcise ghosts for money' } },
    { word: 'Bunty Aur Babli 2', difficulty: 'medium',
      hints: { cast: 'Saif Ali Khan, Rani Mukerji, Siddhant Chaturvedi', year: '2021', genre: 'Comedy / Crime', tagline: 'The original con artists vs the new ones' } },
    { word: 'Radhe Shyam', difficulty: 'medium',
      hints: { cast: 'Prabhas, Pooja Hegde', year: '2022', genre: 'Romance / Drama', tagline: 'A palmist who cannot fall in love — 1970s Europe' } },

    // ── Hard (30 — older/obscure Hindi films) ─────────────────────────────────
    { word: 'Jaane Bhi Do Yaaron', difficulty: 'hard',
      hints: { cast: 'Naseeruddin Shah, Ravi Baswani', year: '1983', genre: 'Black Comedy / Satire', tagline: 'Photographers uncover a corruption scandal' } },
    { word: 'Maqbool', difficulty: 'hard',
      hints: { cast: 'Irrfan Khan, Tabu, Pankaj Kapur', year: '2003', genre: 'Crime / Drama', tagline: 'Macbeth retold in Mumbai underworld' } },
    { word: 'Masaan', difficulty: 'hard',
      hints: { cast: 'Richa Chadha, Vicky Kaushal, Sanjay Mishra', year: '2015', genre: 'Drama', tagline: 'Two stories of love and loss on the banks of the Ganga' } },
    { word: 'Peepli Live', difficulty: 'hard',
      hints: { cast: 'Omkar Das Manikpuri, Malaika Shenoy', year: '2010', genre: 'Satirical Comedy', tagline: 'Media circus around a farming family suicide threat' } },
    { word: 'Hazaaron Khwaishein Aisi', difficulty: 'hard',
      hints: { cast: 'Shiney Ahuja, Kay Kay Menon', year: '2003', genre: 'Drama / Political', tagline: '1970s Naxal movement — love and ideology' } },
    { word: 'Dil Se', difficulty: 'hard',
      hints: { cast: 'Shah Rukh Khan, Manisha Koirala', year: '1998', genre: 'Drama / Thriller', tagline: 'Chaiyya Chaiyya — a journalist falls for a militant' } },
    { word: 'Satya', difficulty: 'hard',
      hints: { cast: 'Chakravarthy, Manoj Bajpayee, Urmila Matondkar', year: '1998', genre: 'Crime / Drama', tagline: 'Bharat Mata Ki Jai — Mumbai underworld' } },
    { word: 'Bandit Queen', difficulty: 'hard',
      hints: { cast: 'Seema Biswas', year: '1994', genre: 'Biopic / Drama', tagline: 'Phoolan Devi — from victim to dacoit' } },
    { word: 'Mirch Masala', difficulty: 'hard',
      hints: { cast: 'Smita Patil, Naseeruddin Shah', year: '1987', genre: 'Drama', tagline: 'A village woman defies a corrupt official' } },
    { word: 'Ankur', difficulty: 'hard',
      hints: { cast: 'Shabana Azmi, Anant Nag', year: '1974', genre: 'Drama', tagline: 'Seeds of exploitation — feudal landlord and servant' } },
    { word: 'Arth', difficulty: 'hard',
      hints: { cast: 'Shabana Azmi, Smita Patil', year: '1982', genre: 'Drama', tagline: 'A woman rebuilds her life after marital betrayal' } },
    { word: 'Bhumika', difficulty: 'hard',
      hints: { cast: 'Smita Patil, Naseeruddin Shah', year: '1977', genre: 'Drama / Biopic', tagline: 'Based on actress Hansa Wadkar turbulent life' } },
    { word: 'Manthan', difficulty: 'hard',
      hints: { cast: 'Girish Karnad, Smita Patil', year: '1976', genre: 'Drama', tagline: 'White revolution — Amul dairy cooperative' } },
    { word: 'Sparsh', difficulty: 'hard',
      hints: { cast: 'Naseeruddin Shah, Shabana Azmi', year: '1980', genre: 'Drama', tagline: 'A blind school principal finds love' } },
    { word: 'Ardh Satya', difficulty: 'hard',
      hints: { cast: 'Om Puri, Smita Patil', year: '1983', genre: 'Crime / Drama', tagline: 'Half truth — a police officer vs a corrupt system' } },
    { word: 'Naseem', difficulty: 'hard',
      hints: { cast: 'Kaifi Azmi, Mayuri Kango', year: '1995', genre: 'Drama / Political', tagline: 'Babri Masjid demolition seen through a young girl' } },
    { word: 'Tamas', difficulty: 'hard',
      hints: { cast: 'Om Puri, Deepa Sahi', year: '1988', genre: 'Drama / Historical', tagline: 'Darkness — partition violence saga' } },
    { word: 'Damul', difficulty: 'hard',
      hints: { cast: 'Manohar Singh, Deepti Naval', year: '1985', genre: 'Drama', tagline: 'Bonded labour in Bihar village' } },
    { word: 'Paar', difficulty: 'hard',
      hints: { cast: 'Naseeruddin Shah, Shabana Azmi', year: '1984', genre: 'Drama', tagline: 'Crossing a river to flee caste violence' } },
    { word: 'Aakrosh', difficulty: 'hard',
      hints: { cast: 'Om Puri, Naseeruddin Shah, Smita Patil', year: '1980', genre: 'Crime / Drama', tagline: 'Silent rage — tribal man accused of murdering his wife' } },
    { word: 'Nishant', difficulty: 'hard',
      hints: { cast: 'Girish Karnad, Shabana Azmi', year: '1975', genre: 'Drama', tagline: "Night's end — zamindari men abduct a schoolmaster's wife" } },
    { word: 'Vijeta', difficulty: 'hard',
      hints: { cast: 'Shashi Kapoor, Rekha', year: '1982', genre: 'Drama', tagline: "A young man's coming of age as an Air Force pilot" } },
    { word: 'Khandhar', difficulty: 'hard',
      hints: { cast: 'Naseeruddin Shah, Shabana Azmi', year: '1984', genre: 'Drama', tagline: 'The ruins — photographer revisits a crumbling mansion' } },
    { word: 'Albert Pinto Ko Gussa Kyoon Aata Hai', difficulty: 'hard',
      hints: { cast: 'Naseeruddin Shah, Smita Patil', year: '1980', genre: 'Drama', tagline: "A car mechanic's political awakening" } },
    { word: 'Suraj Ka Satvan Ghoda', difficulty: 'hard',
      hints: { cast: 'Rajit Kapur', year: '1992', genre: 'Drama', tagline: 'Seven interlocking love stories told in one evening' } },
    { word: 'Pestonjee', difficulty: 'hard',
      hints: { cast: 'Naseeruddin Shah, Anupam Kher', year: '1988', genre: 'Drama', tagline: 'Parsi friends and the woman between them' } },
    { word: 'Tarang', difficulty: 'hard',
      hints: { cast: 'Om Puri, Smita Patil', year: '1984', genre: 'Drama', tagline: 'Class conflict — worker vs capitalist family' } },
    { word: 'Chakra', difficulty: 'hard',
      hints: { cast: 'Naseeruddin Shah, Smita Patil', year: '1981', genre: 'Drama', tagline: 'Life in a Mumbai slum' } },
    { word: 'Haider', difficulty: 'hard',
      hints: { cast: 'Shahid Kapoor, Tabu, Kay Kay Menon', year: '2014', genre: 'Thriller / Drama', tagline: 'Hamlet retold in Kashmir — Chuzhawan' } },
    { word: 'Lootera', difficulty: 'hard',
      hints: { cast: 'Ranveer Singh, Sonakshi Sinha', year: '2013', genre: 'Drama / Romance', tagline: 'Art, love and deception in 1950s Bengal' } },
  ]
}

const bollywood_songs = {
  label: 'Bollywood Songs',
  emoji: '🎵',
  words: [
    // Easy (20)
    { word: 'Jai Ho',                     difficulty: 'easy' },
    { word: 'Dilbar Dilbar',              difficulty: 'easy' },
    { word: 'Chaiyya Chaiyya',            difficulty: 'easy' },
    { word: 'Kajra Re',                   difficulty: 'easy' },
    { word: 'Dola Re Dola',               difficulty: 'easy' },
    { word: 'Kuch Kuch Hota Hai',         difficulty: 'easy' },
    { word: 'Tujhe Dekha Toh',            difficulty: 'easy' },
    { word: 'Rang De Basanti',            difficulty: 'easy' },
    { word: 'Ek Do Teen',                 difficulty: 'easy' },
    { word: 'Humma Humma',                difficulty: 'easy' },
    { word: 'Tu Cheez Badi Hai',          difficulty: 'easy' },
    { word: 'Jumma Chumma',               difficulty: 'easy' },
    { word: 'Ole Ole',                    difficulty: 'easy' },
    { word: 'Aankh Maare',                difficulty: 'easy' },
    { word: 'Bom Diggy Diggy',            difficulty: 'easy' },
    { word: 'Kar Gayi Chull',             difficulty: 'easy' },
    { word: 'Badtameez Dil',              difficulty: 'easy' },
    { word: 'Gallan Goodiyaan',           difficulty: 'easy' },
    { word: 'Tune Maari Entriyaan',       difficulty: 'easy' },
    { word: 'Desi Girl',                  difficulty: 'easy' },
    // Medium (25)
    { word: 'Tanhayee',                   difficulty: 'medium' },
    { word: 'Alvida',                     difficulty: 'medium' },
    { word: 'Kabira',                     difficulty: 'medium' },
    { word: 'Phir Le Aya Dil',            difficulty: 'medium' },
    { word: 'Tum Hi Ho',                  difficulty: 'medium' },
    { word: 'Agar Tum Saath Ho',          difficulty: 'medium' },
    { word: 'Channa Mereya',              difficulty: 'medium' },
    { word: 'Raabta',                     difficulty: 'medium' },
    { word: 'Ae Dil Hai Mushkil',         difficulty: 'medium' },
    { word: 'Bulleya',                    difficulty: 'medium' },
    { word: 'Ik Vaari Aa',                difficulty: 'medium' },
    { word: 'Gerua',                      difficulty: 'medium' },
    { word: 'Teri Mitti',                 difficulty: 'medium' },
    { word: 'Kesariya',                   difficulty: 'medium' },
    { word: 'Lut Gaye',                   difficulty: 'medium' },
    { word: 'Srivalli',                   difficulty: 'medium' },
    { word: 'Pushpa Pushpa',              difficulty: 'medium' },
    { word: 'Naacho Naacho',              difficulty: 'medium' },
    { word: 'Apna Bana Le',               difficulty: 'medium' },
    { word: 'Bekhayali',                  difficulty: 'medium' },
    { word: 'Pachtaoge',                  difficulty: 'medium' },
    { word: 'Dil Diyan Gallan',           difficulty: 'medium' },
    { word: 'Ve Maahi',                   difficulty: 'medium' },
    { word: 'Manike Mage Hithe',          difficulty: 'medium' },
    { word: 'Saami Saami',                difficulty: 'medium' },
    // Hard (15)
    { word: 'Dum Maro Dum',               difficulty: 'hard' },
    { word: 'Piya Tose Naina Laage Re',   difficulty: 'hard' },
    { word: 'Mere Desh Ki Dharti',        difficulty: 'hard' },
    { word: 'Aaj Phir Jeene Ki Tamanna',  difficulty: 'hard' },
    { word: 'Waqt Ne Kiya Kya Haseen Sitam', difficulty: 'hard' },
    { word: 'Lag Ja Gale',                difficulty: 'hard' },
    { word: 'Ajeeb Dastan Hai Yeh',       difficulty: 'hard' },
    { word: 'Mera Joota Hai Japani',      difficulty: 'hard' },
    { word: 'Abhi Na Jao Chhod Kar',      difficulty: 'hard' },
    { word: 'Ye Mera Deewanapan Hai',     difficulty: 'hard' },
    { word: 'Ek Pyar Ka Nagma Hai',       difficulty: 'hard' },
    { word: 'Tere Bina Zindagi Se Koi',   difficulty: 'hard' },
    { word: 'Gulabi Aankhen',             difficulty: 'hard' },
    { word: 'O Saathi Re',                difficulty: 'hard' },
    { word: 'Kabhi Kabhi Mere Dil Mein',  difficulty: 'hard' },
  ]
}

const bollywood_stars = {
  label: 'Bollywood Stars',
  emoji: '⭐',
  words: [
    // Easy (25)
    { word: 'Shah Rukh Khan',             difficulty: 'easy' },
    { word: 'Salman Khan',                difficulty: 'easy' },
    { word: 'Aamir Khan',                 difficulty: 'easy' },
    { word: 'Akshay Kumar',               difficulty: 'easy' },
    { word: 'Amitabh Bachchan',           difficulty: 'easy' },
    { word: 'Deepika Padukone',           difficulty: 'easy' },
    { word: 'Priyanka Chopra',            difficulty: 'easy' },
    { word: 'Katrina Kaif',               difficulty: 'easy' },
    { word: 'Kareena Kapoor',             difficulty: 'easy' },
    { word: 'Hrithik Roshan',             difficulty: 'easy' },
    { word: 'Ranbir Kapoor',              difficulty: 'easy' },
    { word: 'Ranveer Singh',              difficulty: 'easy' },
    { word: 'Alia Bhatt',                 difficulty: 'easy' },
    { word: 'Tiger Shroff',               difficulty: 'easy' },
    { word: 'Sanjay Dutt',                difficulty: 'easy' },
    { word: 'Ajay Devgn',                 difficulty: 'easy' },
    { word: 'Govinda',                    difficulty: 'easy' },
    { word: 'Anil Kapoor',                difficulty: 'easy' },
    { word: 'Madhuri Dixit',              difficulty: 'easy' },
    { word: 'Kajol',                      difficulty: 'easy' },
    { word: 'Aishwarya Rai',              difficulty: 'easy' },
    { word: 'Sunny Deol',                 difficulty: 'easy' },
    { word: 'John Abraham',               difficulty: 'easy' },
    { word: 'Varun Dhawan',               difficulty: 'easy' },
    { word: 'Shraddha Kapoor',            difficulty: 'easy' },
    // Medium (39)
    { word: 'Nawazuddin Siddiqui',        difficulty: 'medium' },
    { word: 'Irrfan Khan',                difficulty: 'medium' },
    { word: 'Pankaj Tripathi',            difficulty: 'medium' },
    { word: 'Manoj Bajpayee',             difficulty: 'medium' },
    { word: 'Rajkummar Rao',              difficulty: 'medium' },
    { word: 'Ayushmann Khurrana',         difficulty: 'medium' },
    { word: 'Vicky Kaushal',              difficulty: 'medium' },
    { word: 'Kartik Aaryan',              difficulty: 'medium' },
    { word: 'Taapsee Pannu',              difficulty: 'medium' },
    { word: 'Kangana Ranaut',             difficulty: 'medium' },
    { word: 'Vidya Balan',                difficulty: 'medium' },
    { word: 'Dimple Kapadia',             difficulty: 'medium' },
    { word: 'Rekha',                      difficulty: 'medium' },
    { word: 'Hema Malini',                difficulty: 'medium' },
    { word: 'Dharmendra',                 difficulty: 'medium' },
    { word: 'Mithun Chakraborty',         difficulty: 'medium' },
    { word: 'Jackie Shroff',              difficulty: 'medium' },
    { word: 'Nora Fatehi',                difficulty: 'medium' },
    { word: 'Kriti Sanon',                difficulty: 'medium' },
    { word: 'Disha Patani',               difficulty: 'medium' },
    { word: 'Bhumi Pednekar',             difficulty: 'medium' },
    { word: 'Sanya Malhotra',             difficulty: 'medium' },
    { word: 'Yami Gautam',                difficulty: 'medium' },
    { word: 'Sonakshi Sinha',             difficulty: 'medium' },
    { word: 'Prabhas',                    difficulty: 'medium' },
    { word: 'Allu Arjun',                 difficulty: 'medium' },
    { word: 'Vijay Deverakonda',          difficulty: 'medium' },
    { word: 'Ram Charan',                 difficulty: 'medium' },
    { word: 'Jr NTR',                     difficulty: 'medium' },
    { word: 'Mahesh Babu',                difficulty: 'medium' },
    { word: 'Vijay',                      difficulty: 'medium' },
    { word: 'Rajinikanth',                difficulty: 'medium' },
    { word: 'Radhika Apte',               difficulty: 'medium' },
    { word: 'Fatima Sana Shaikh',         difficulty: 'medium' },
    { word: 'Tamannaah Bhatia',           difficulty: 'medium' },
    { word: 'Konkona Sen Sharma',         difficulty: 'medium' },
    { word: 'Arjun Kapoor',               difficulty: 'medium' },
    { word: 'Emraan Hashmi',              difficulty: 'medium' },
    { word: 'Arjun Rampal',               difficulty: 'medium' },
    // Hard (16 — character actors / golden-era stars)
    { word: 'Naseeruddin Shah',           difficulty: 'hard' },
    { word: 'Om Puri',                    difficulty: 'hard' },
    { word: 'Shabana Azmi',               difficulty: 'hard' },
    { word: 'Nana Patekar',               difficulty: 'hard' },
    { word: 'Anupam Kher',                difficulty: 'hard' },
    { word: 'Paresh Rawal',               difficulty: 'hard' },
    { word: 'Tabu',                       difficulty: 'hard' },
    { word: 'Swara Bhaskar',              difficulty: 'hard' },
    { word: 'Richa Chadha',               difficulty: 'hard' },
    { word: 'Seema Pahwa',                difficulty: 'hard' },
    { word: 'Ratna Pathak Shah',          difficulty: 'hard' },
    { word: 'Boman Irani',                difficulty: 'hard' },
    { word: 'Gulshan Grover',             difficulty: 'hard' },
    { word: 'Amrish Puri',                difficulty: 'hard' },
    { word: 'Danny Denzongpa',            difficulty: 'hard' },
    { word: 'Pran',                       difficulty: 'hard' },
  ]
}

const indian_tv_shows = {
  label: 'Indian TV Shows',
  emoji: '📺',
  words: [
    // Easy (20)
    { word: 'Taarak Mehta Ka Ooltah Chashmah', difficulty: 'easy' },
    { word: 'KBC',                        difficulty: 'easy' },
    { word: 'Bigg Boss',                  difficulty: 'easy' },
    { word: 'Indian Idol',                difficulty: 'easy' },
    { word: 'CID',                        difficulty: 'easy' },
    { word: 'Crime Patrol',               difficulty: 'easy' },
    { word: 'Kapil Sharma Show',          difficulty: 'easy' },
    { word: 'Shaktimaan',                 difficulty: 'easy' },
    { word: 'Ramayan',                    difficulty: 'easy' },
    { word: 'Mahabharat',                 difficulty: 'easy' },
    { word: 'Balika Vadhu',               difficulty: 'easy' },
    { word: 'Yeh Rishta Kya Kehlata Hai', difficulty: 'easy' },
    { word: 'Sarabhai vs Sarabhai',       difficulty: 'easy' },
    { word: 'Office Office',              difficulty: 'easy' },
    { word: 'Mirzapur',                   difficulty: 'easy' },
    { word: 'Scam 1992',                  difficulty: 'easy' },
    { word: 'The Family Man',             difficulty: 'easy' },
    { word: 'Panchayat',                  difficulty: 'easy' },
    { word: 'Sacred Games',               difficulty: 'easy' },
    { word: 'Byomkesh Bakshi',            difficulty: 'easy' },
    // Medium (20)
    { word: 'Aspirants',                  difficulty: 'medium' },
    { word: 'Kota Factory',               difficulty: 'medium' },
    { word: 'TVF Pitchers',               difficulty: 'medium' },
    { word: 'Permanent Roommates',        difficulty: 'medium' },
    { word: 'Rocket Boys',                difficulty: 'medium' },
    { word: 'Jamtara',                    difficulty: 'medium' },
    { word: 'Delhi Crime',                difficulty: 'medium' },
    { word: 'Inside Edge',                difficulty: 'medium' },
    { word: 'Flames',                     difficulty: 'medium' },
    { word: 'Hostel Daze',                difficulty: 'medium' },
    { word: 'College Romance',            difficulty: 'medium' },
    { word: 'Khichdi',                    difficulty: 'medium' },
    { word: 'Dekh Bhai Dekh',             difficulty: 'medium' },
    { word: 'Hip Hip Hurray',             difficulty: 'medium' },
    { word: 'Just Mohabbat',              difficulty: 'medium' },
    { word: 'Ek Mahal Ho Sapno Ka',       difficulty: 'medium' },
    { word: 'Woh Rehne Waali Mehlon Ki',  difficulty: 'medium' },
    { word: 'Tanha Tanha',                difficulty: 'medium' },
    { word: 'Breathe',                    difficulty: 'medium' },
    { word: 'Bhuvan Bam BB Ki Vines',     difficulty: 'medium' },
    // Hard (10 — classic Doordarshan era)
    { word: 'Nukkad',                     difficulty: 'hard' },
    { word: 'Hum Log',                    difficulty: 'hard' },
    { word: 'Buniyaad',                   difficulty: 'hard' },
    { word: 'Wagle Ki Duniya',            difficulty: 'hard' },
    { word: 'Fauji',                      difficulty: 'hard' },
    { word: 'Circus',                     difficulty: 'hard' },
    { word: 'Flop Show',                  difficulty: 'hard' },
    { word: 'Zabaan Sambhal Ke',          difficulty: 'hard' },
    { word: 'Turning Point',              difficulty: 'hard' },
    { word: 'Sea Hawks',                  difficulty: 'hard' },
  ]
}

const indian_cricketers = {
  label: 'Indian Cricketers',
  emoji: '🏏',
  words: [
    // Easy (20)
    { word: 'Sachin Tendulkar',           difficulty: 'easy' },
    { word: 'MS Dhoni',                   difficulty: 'easy' },
    { word: 'Virat Kohli',                difficulty: 'easy' },
    { word: 'Rohit Sharma',               difficulty: 'easy' },
    { word: 'Sourav Ganguly',             difficulty: 'easy' },
    { word: 'Anil Kumble',                difficulty: 'easy' },
    { word: 'Kapil Dev',                  difficulty: 'easy' },
    { word: 'Sunil Gavaskar',             difficulty: 'easy' },
    { word: 'Yuvraj Singh',               difficulty: 'easy' },
    { word: 'Harbhajan Singh',            difficulty: 'easy' },
    { word: 'Zaheer Khan',                difficulty: 'easy' },
    { word: 'VVS Laxman',                 difficulty: 'easy' },
    { word: 'Rahul Dravid',               difficulty: 'easy' },
    { word: 'Sehwag',                     difficulty: 'easy' },
    { word: 'Shikhar Dhawan',             difficulty: 'easy' },
    { word: 'Hardik Pandya',              difficulty: 'easy' },
    { word: 'Jasprit Bumrah',             difficulty: 'easy' },
    { word: 'Ravindra Jadeja',            difficulty: 'easy' },
    { word: 'KL Rahul',                   difficulty: 'easy' },
    { word: 'Shubman Gill',               difficulty: 'easy' },
    // Medium (20)
    { word: 'Mohinder Amarnath',          difficulty: 'medium' },
    { word: 'Dilip Vengsarkar',           difficulty: 'medium' },
    { word: 'Sandeep Patil',              difficulty: 'medium' },
    { word: 'Ravi Shastri',               difficulty: 'medium' },
    { word: 'Manoj Prabhakar',            difficulty: 'medium' },
    { word: 'Ajay Jadeja',                difficulty: 'medium' },
    { word: 'Nayan Mongia',               difficulty: 'medium' },
    { word: 'Javagal Srinath',            difficulty: 'medium' },
    { word: 'Venkatesh Prasad',           difficulty: 'medium' },
    { word: 'Ajit Agarkar',               difficulty: 'medium' },
    { word: 'Yusuf Pathan',               difficulty: 'medium' },
    { word: 'Irfan Pathan',               difficulty: 'medium' },
    { word: 'Sreesanth',                  difficulty: 'medium' },
    { word: 'Munaf Patel',                difficulty: 'medium' },
    { word: 'Dinesh Karthik',             difficulty: 'medium' },
    { word: 'Ambati Rayudu',              difficulty: 'medium' },
    { word: 'Suresh Raina',               difficulty: 'medium' },
    { word: 'Axar Patel',                 difficulty: 'medium' },
    { word: 'Shardul Thakur',             difficulty: 'medium' },
    { word: 'RP Singh',                   difficulty: 'medium' },
    // Hard (10 — golden-era pre-1990)
    { word: 'Polly Umrigar',              difficulty: 'hard' },
    { word: 'Vijay Hazare',               difficulty: 'hard' },
    { word: 'Lala Amarnath',              difficulty: 'hard' },
    { word: 'Vinoo Mankad',               difficulty: 'hard' },
    { word: 'Chandu Borde',               difficulty: 'hard' },
    { word: 'Bapu Nadkarni',              difficulty: 'hard' },
    { word: 'Salim Durani',               difficulty: 'hard' },
    { word: 'Hanumant Singh',             difficulty: 'hard' },
    { word: 'Abid Ali',                   difficulty: 'hard' },
    { word: 'Syed Abid Ali',              difficulty: 'hard' },
  ]
}

export const WORD_PACKS = {
  bollywood_movies:  bollywood_movies,
  bollywood_songs:   bollywood_songs,
  bollywood_stars:   bollywood_stars,
  indian_tv_shows:   indian_tv_shows,
  indian_cricketers: indian_cricketers,
}

/**
 * Build a shuffled word pool from selected categories + difficulty.
 * difficulty ladder: easy → [easy], medium → [easy, medium], hard/mixed → [easy, medium, hard]
 * @param {string[]} categoryKeys
 * @param {string}   difficulty  — 'easy'|'medium'|'hard'|'mixed'
 * @param {string[]} customWords — always included
 * @returns {string[]} deduplicated words
 */
export function buildWordPool(categoryKeys, difficulty, customWords = []) {
  const diffPool = {
    easy:   new Set(['easy']),
    medium: new Set(['easy', 'medium']),
    hard:   new Set(['easy', 'medium', 'hard']),
    mixed:  new Set(['easy', 'medium', 'hard']),
  }
  const allowed = diffPool[difficulty] ?? diffPool.easy

  const packWords = categoryKeys
    .flatMap(key => {
      const pack = WORD_PACKS[key]
      if (!pack) return []
      return pack.words.filter(w => allowed.has(w.difficulty)).map(w => w.word)
    })

  return [...new Set([...packWords, ...customWords])]
}

export function shuffleArray(arr) {
  const copy = [...arr]
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}
